{
  "hash": "b8f9bfc3b4016e2843d02b1396751b7b",
  "result": {
    "markdown": "::: {.content-hidden unless-format=\"html\"}\n$$\n\\newcommand{\\tr}{\\mathrm{tr}}\n\\newcommand{\\rank}{\\mathrm{rank}}\n\\newcommand{\\plim}{\\operatornamewithlimits{plim}}\n\\newcommand{\\diag}{\\mathrm{diag}}\n\\newcommand{\\bm}[1]{\\boldsymbol{\\mathbf{#1}}}\n\\newcommand{\\Var}{\\mathrm{Var}}\n\\newcommand{\\Exp}{\\mathrm{E}}\n\\newcommand{\\Cov}{\\mathrm{Cov}}\n\\newcommand\\given[1][]{\\:#1\\vert\\:}\n\\newcommand{\\irow}[1]{%\n\\begin{pmatrix}#1\\end{pmatrix}\n}\n$$\n:::\n\n# Spatial Impacts\n\n### Required packages {.unnumbered}\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-1_128bb0bdd1e5a0f7e476166eaf7a39fe'}\n\n```{.r .cell-code}\npkgs <- c(\"sf\", \"mapview\", \"spdep\", \"spatialreg\", \"tmap\", \"viridisLite\") # note: load spdep first, then spatialreg\nlapply(pkgs, require, character.only = TRUE)\n```\n:::\n\n\n\n### Session info {.unnumbered}\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-2_24fd5813436345c5ce61ea3a9fcfb4ee'}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.4.1 (2024-06-14 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 22631)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United Kingdom.utf8 \n[2] LC_CTYPE=English_United Kingdom.utf8   \n[3] LC_MONETARY=English_United Kingdom.utf8\n[4] LC_NUMERIC=C                           \n[5] LC_TIME=English_United Kingdom.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] viridisLite_0.4.2 tmap_3.3-4        spatialreg_1.3-4  Matrix_1.7-0     \n[5] spdep_1.3-5       spData_2.3.1      mapview_2.11.2    sf_1.0-16        \n\nloaded via a namespace (and not attached):\n [1] xfun_0.45          raster_3.6-26      htmlwidgets_1.6.4  lattice_0.22-6    \n [5] tools_4.4.1        crosstalk_1.2.1    LearnBayes_2.15.1  parallel_4.4.1    \n [9] stats4_4.4.1       sandwich_3.1-0     proxy_0.4-27       KernSmooth_2.23-24\n[13] satellite_1.0.5    RColorBrewer_1.1-3 leaflet_2.2.2      lifecycle_1.0.4   \n[17] compiler_4.4.1     deldir_2.0-4       munsell_0.5.1      terra_1.7-78      \n[21] codetools_0.2-20   leafsync_0.1.0     stars_0.6-5        htmltools_0.5.8.1 \n[25] class_7.3-22       MASS_7.3-60.2      classInt_0.4-10    lwgeom_0.2-14     \n[29] wk_0.9.1           abind_1.4-5        boot_1.3-30        multcomp_1.4-25   \n[33] nlme_3.1-164       digest_0.6.35      mvtnorm_1.2-5      splines_4.4.1     \n[37] fastmap_1.2.0      grid_4.4.1         colorspace_2.1-0   cli_3.6.2         \n[41] magrittr_2.0.3     base64enc_0.1-3    dichromat_2.0-0.1  XML_3.99-0.16.1   \n[45] survival_3.6-4     leafem_0.2.3       TH.data_1.1-2      e1071_1.7-14      \n[49] scales_1.3.0       sp_2.1-4           rmarkdown_2.27     zoo_1.8-12        \n[53] png_0.1-8          coda_0.19-4.1      evaluate_0.24.0    knitr_1.47        \n[57] tmaptools_3.1-1    s2_1.1.6           rlang_1.1.4        Rcpp_1.0.12       \n[61] glue_1.7.0         DBI_1.2.3          rstudioapi_0.16.0  jsonlite_1.8.8    \n[65] R6_2.5.1           units_0.8-5       \n```\n:::\n:::\n\n\n\n### Reload data from pervious session {.unnumbered}\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-3_51c6eaaa1a4155a698887eed833ed5a1'}\n\n```{.r .cell-code}\nload(\"_data/msoa2_spatial.RData\")\n```\n:::\n\n::: {.cell hash='07_impacts_cache/pdf/regression-results_c37a7223f44f09969687d33ae65c152a'}\n\n:::\n\n\n\n\n## Coefficient estimates $\\neq$ `marginal' effects\n\n::: callout-warning\nDo not interpret coefficients as marginal effects in SAR, SAC, and SDM!! \n:::\n\nAt first glance, the specifications presented above seem relatively similar in the way of modelling spatial effects. **Yet, they differ in very important aspects**. \n\nFirst, models with an endogenous spatial term (SAR, SAC, and SDM) assume a very different spatial dependence structure than models with only exogenous spatial terms as SLX and SDEM specifications. While the first three assume **global** spatial dependence, the second two assume **local** spatial dependence [@Anselin.2003; @HalleckVega.2015; @LeSage.2009]. \n\nSecond, the interpretation of the coefficients differs greatly between models with and without endogenous effects. This becomes apparent when considering the reduced form of the equations above. Exemplary using the SAR model, the reduced form is given by:\n\n$$\n\\begin{split}\n{\\bm y}-\\rho{\\bm W}{\\bm y} &={\\bm X}{\\bm \\beta}+ {\\bm \\varepsilon}, \\nonumber \\\\\n({\\bm I_N}-\\rho {\\bm W}){\\bm y} &={\\bm X}{\\bm \\beta}+ {\\bm \\varepsilon}\\nonumber, \\\\\n{\\bm y} &=({\\bm I_N}-\\rho {\\bm W})^{-1}({\\bm X}{\\bm \\beta}+ {\\bm \\varepsilon}),\n\\end{split}\n$$\n\nwhere ${\\bm I_N}$ is an $N \\times N$ diagonal matrix (diagonal elements equal 1, 0 otherwise). This contains no spatially lagged dependent variable on the right-hand side.\n\nIf we want to interpret coefficient, we are usually in marginal or partial effects (the association between a unit change in $X$ and $Y$). We obtain these effects by looking at the first derivative.\n\nWhen taking the first derivative of the explanatory variable ${\\bm x}_k$ from the reduced form in (\\ref{eq:sarred}) to interpret the partial effect of a unit change in variable ${\\bm x}_k$ on ${\\bm y}$, we receive\n\n$$\n\\frac{\\partial {\\bm y}}{\\partial {\\bm x}_k}=\\underbrace{({\\bm I_N}-\\rho {\\bm W})^{-1}}_{N \\times N}\\beta_k,\n$$\n\nfor each covariate $k=\\{1,2,...,K\\}$. As can be seen, the partial derivative with respect to ${\\bm x}_k$ produces an $N \\times N$ matrix, thereby representing the partial effect of each unit $i$ onto the focal unit $i$ itself and all other units \\textcolor{red}{$j=\\{1,2,...,i-1,i+1,...,N\\}$}. \n\nNote that the diagonal elements of $({\\bm I_N}-\\rho {\\bm W})^{-1}$ are not zero anymore (as they are in $\\bm W$). Look at the following minimal example:\n\n$$\n\\begin{split}\n\\tilde{\\bm W} = \\begin{pmatrix}\n      0 & 1 & 0 & 1 & 0 \\\\\n      1 & 0 & 1 & 0 & 1 \\\\\n      0 & 1 & 0 & 1 & 0 \\\\\n      1 & 0 & 1 & 0 & 1 \\\\\n      0 & 1 & 0 & 1 & 0\n      \\end{pmatrix}, \\mathrm{and~normalized} ~\n\\bm W = \\begin{pmatrix}\n      0 & 0.5 & 0 & 0.5 & 0 \\\\\n      0.33 & 0 & 0.33 & 0 & 0.33 \\\\\n      0 & 0.5 & 0 & 0.5 & 0 \\\\\n      0.33 & 0 & 0.33 & 0 & 0.33 \\\\\n      0 & 0.5 & 0 & 0.5 & 0\n      \\end{pmatrix}      \n\\end{split}\n$$\n\nand \n\n$$\n\\rho = 0.6,\n$$\n\nthen \n\n$$\n\\begin{split}\n\\rho \\bm W = \\begin{pmatrix}\n      0 & 0.3 & 0 & 0.3 & 0 \\\\\n      0.2 & 0 & 0.2 & 0 & 0.2 \\\\\n      0 & 0.3 & 0 & 0.3 & 0 \\\\\n      0.2 & 0 & 0.2 & 0 & 0.2 \\\\\n      0 & 0.3 & 0 & 0.3 & 0\n      \\end{pmatrix}.\n\\end{split}\n$$\n\nIf we want to get the total effect of $X$ on $Y$ we need to add the direct association within $i$ and $j$ and so on... \n\n$$\n\\begin{split}\n\\bm I_N - \\rho \\bm W &=\n\\begin{pmatrix}\n      1 & 0 & 0 & 0 & 0 \\\\\n      0 & 1 & 0 & 0 & 0 \\\\\n      0 & 0 & 1 & 0 & 0 \\\\\n      0 & 0 & 0 & 1 & 0 \\\\\n      0 & 1 & 0 & 0 & 1\n      \\end{pmatrix} - \n\\begin{pmatrix}\n      0 & 0.3 & 0 & 0.3 & 0 \\\\\n      0.2 & 0 & 0.2 & 0 & 0.2 \\\\\n      0 & 0.3 & 0 & 0.3 & 0 \\\\\n      0.2 & 0 & 0.2 & 0 & 0.2 \\\\\n      0 & 0.3 & 0 & 0.3 & 0\n      \\end{pmatrix}\\\\\n& = \\begin{pmatrix}\n      1 & -0.3 & 0 & -0.3 & 0 \\\\\n      -0.2 & 1 & -0.2 & 0 & -0.2 \\\\\n      0 & 0.3 & 1 & 0.3 & 0 \\\\\n      -0.2 & 0 & -0.2 & 1 & -0.2 \\\\\n      0 & -0.3 & 0 & -0.3 & 1\n      \\end{pmatrix}.\n\\end{split}\n$$\n\nAnd finally we take the inverse of that\n\n$$\n\\begin{split}\n(\\bm I_N - \\rho \\bm W)^{-1} &=\n\\begin{pmatrix}\n      1 & -0.3 & 0 & -0.3 & 0 \\\\\n      -0.2 & 1 & -0.2 & 0 & -0.2 \\\\\n      0 & 0.3 & 1 & 0.3 & 0 \\\\\n      -0.2 & 0 & -0.2 & 1 & -0.2 \\\\\n      0 & -0.3 & 0 & -0.3 & 1\n      \\end{pmatrix}^{-1}\\\\\n&=\n\\begin{pmatrix}\n      \\color{red}{1.1875} & 0.46875 & 0.1875 & 0.46875 & 0.1875 \\\\\n      0.3125 & \\color{red}{1.28125} & 0.3125 & 0.28125 & 0.3125 \\\\\n      0.1875 & 0.46875 & \\color{red}{1.1875} & 0.46875 & 0.1875 \\\\\n      0.3125 & 0.28125 & 0.3125 & \\color{red}{1.28125} & 0.3125 \\\\\n      0.1875 & 0.46875 & 0.1875 & 0.46875 & \\color{red}{1.1875}\n      \\end{pmatrix}.\n\\end{split}\n$$\n\nAs you can see, $(\\bm I_N - \\rho \\bm W)^{-1}$ has \\color{red}{diagonal elements} $>1$: these are feedback loops. My $X$ influences my $Y$ directly, but my $Y$ then influences my neigbour's $Y$, which then influences my $Y$ again (also also other neighbour's $Y$s). Thus the influence of my $X$ on my $Y$ includes a spatial multiplier.\n\nCheck yourself:\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-4_6675d5d2b7baad74fa1c12f0aa073188'}\n\n```{.r .cell-code}\nI = diag(5)\nrho = 0.6\nW = matrix(c(0 , 0.5 , 0 , 0.5 , 0,\n            1/3 , 0 , 1/3 , 0 , 1/3,\n            0 , 0.5 , 0 , 0.5 , 0,\n            1/3 , 0 , 1/3 , 0 , 1/3,\n            0 , 0.5 , 0 , 0.5 , 0), ncol = 5, byrow = TRUE)\n\n(IrW = I - rho*W)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4] [,5]\n[1,]  1.0 -0.3  0.0 -0.3  0.0\n[2,] -0.2  1.0 -0.2  0.0 -0.2\n[3,]  0.0 -0.3  1.0 -0.3  0.0\n[4,] -0.2  0.0 -0.2  1.0 -0.2\n[5,]  0.0 -0.3  0.0 -0.3  1.0\n```\n:::\n\n```{.r .cell-code}\n# (I - rho*W)^-1\n(M = solve(IrW))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       [,1]    [,2]   [,3]    [,4]   [,5]\n[1,] 1.1875 0.46875 0.1875 0.46875 0.1875\n[2,] 0.3125 1.28125 0.3125 0.28125 0.3125\n[3,] 0.1875 0.46875 1.1875 0.46875 0.1875\n[4,] 0.3125 0.28125 0.3125 1.28125 0.3125\n[5,] 0.1875 0.46875 0.1875 0.46875 1.1875\n```\n:::\n:::\n\n\n\nThe diagonal elements of $M$ indicate how each unit $i$ influences itself (change of $x_i$ on change of $y_i$), and each off-diagonal elements in column $j$ represents the effect of $j$ on each other unit $i$ (change of $x_j$ on change of $y_i$). \n\n$$\n\\begin{split}\n\\begin{pmatrix}\n      1.1875 & \\color{red}{0.46875} & 0.1875 & 0.46875 & 0.1875 \\\\\n      0.3125 & 1.28125 & 0.3125 & 0.28125 & 0.3125 \\\\\n      0.1875 & 0.46875 & 1.1875 & 0.46875 & 0.1875 \\\\\n      0.3125 & 0.28125 & 0.3125 & 1.28125 & 0.3125 \\\\\n      0.1875 & 0.46875 & \\color{blue}{0.1875} & 0.46875 & 1.1875\n      \\end{pmatrix}.\n\\end{split}\n$$\n\nFor instance, $\\color{red}{W_{12}}$ indicates that unit 2 has an influence of 0.46875 on unit 1. On the other hand, $\\color{blue}{W_{53}}$ indicates that unit 3 has an influence of magnitude 0.1875 on unit 5.\n\n::: callout-tip\n## Question\n\nWhy does unit 3 have any effect o unit 5? According to $\\bm W$ those two units are no neighbours $w_{53} = 0$!\n:::\n\n\n<!-- $$\t -->\n<!-- \t\\begin{equation} -->\n<!-- \t\\begin{split} -->\n<!-- \t\t{\\bm y} & =\\alpha{\\bm \\iota}+\\rho {\\bm W}{\\bm y}+{\\bm X}{\\bm \\beta}+{\\bm \\varepsilon} \\\\ -->\n<!-- \t\t{\\bm y} & =({\\bm I}-\\rho{\\bm W})^{-1}(\\alpha{\\bm \\iota}+{\\bm X}{\\bm \\beta}+{\\bm \\varepsilon}), -->\n<!-- \t\\end{split} -->\n<!-- \t\\end{equation} -->\n<!-- $$\t -->\n\n<!-- we can calculate the first derivative: -->\n\n<!-- $$\t -->\n<!-- \t\\begin{equation} -->\n<!-- \t\\begin{split} -->\n<!-- \t\t\\frac{\\partial \\bm y}{\\partial \\bm x_k} & = ({\\bm I}-\\rho{\\bm W})^{-1}\\beta_k \\\\ -->\n<!-- \t\t& =({\\bm I} + \\rho{\\bm W} + \\rho^2{\\bm W}^2 + \\rho^3{\\bm W}^3 + ...)\\beta_k,  -->\n<!-- \t\\end{split} -->\n<!-- \t\\end{equation}\t -->\n<!-- $$\t -->\n<!-- \twhere $\\rho{\\bm W}\\beta_k$ equals the effect stemming from direct neighbours, $\\rho^2{\\bm W}^2\\beta_k$ the effect stemming from second order neighbours (neighbours of neighbours),...  -->\n\n<!-- for SAR, SAC, and SDM even the direct impacts differ from the point estimates. This results from the fact that an endogenous term of the dependent variable ${\\bm W}{\\bm y}$ contains feedback loops through the system of neighbours \\citep{Betz.2019,Franzese.2007.0,HalleckVega.2015.0}. A change of $x_{i}$ in the focal unit $i$ influences the focal unit $i$ itself, but also the neighbouring unit $j$, which in turn influences the focal unit $i$ in a feedback loop. This feedback loop is part of the direct impact. -->\n\t\n## Global and local spillovers\n\nThe kind of indirect spillover effects in SAR, SAC, and SDM models differs from the kind of indirect spillover effects in SLX and SDEM models: while the first three specifications represent **global spillover effects**, the latter three represent **local spillover effects** [@Anselin.2003; @LeSage.2009; @LeSage.2014]. \n\n### Local spillovers\n\nIn case of SLX and SDEM the spatial spillover effects can be interpreted as the effect of a one unit change of ${\\bm x}_k$ in the spatially weighted neighbouring observations on the dependent variable of the focal unit: the weighted average among neighbours; when using a row-normalised contiguity weights matrix, ${\\bm W} {\\bm x}_k$ is the mean value of ${\\bm x}_k$ in the neighbouring units. \n\nAssume we have $k =2$ covariates, then\n\n$$\n\\begin{split}\n\\underbrace{\\bm W}_{N \\times N}  \\underbrace{\\bm X}_{N \\times 2} \\underbrace{\\bm \\theta}_{2 \\times 1} & = \n\\begin{pmatrix}\n      0 & 0.5 & 0 & 0.5 & 0 \\\\\n      0.33 & 0 & 0.33 & 0 & 0.33 \\\\\n      0 & 0.5 & 0 & 0.5 & 0 \\\\\n      0.33 & 0 & 0.33 & 0 & 0.33 \\\\\n      0 & 0.5 & 0 & 0.5 & 0\n  \\end{pmatrix}\n  \\begin{pmatrix}\n      3 & 100 \\\\\n      4 & 140 \\\\\n      1 & 200 \\\\\n      7 & 70  \\\\\n      5 & 250 \n  \\end{pmatrix}\n    \\begin{pmatrix}\n      \\theta_1 \\\\\n      \\theta_2 \n  \\end{pmatrix}\\\\\n & =   \n \\begin{pmatrix}\n      6 & 105 \\\\\n      3 & 190 \\\\\n      6 & 105 \\\\\n      3 & 190  \\\\\n      6 & 105 \n  \\end{pmatrix}\n \\begin{pmatrix}\n      \\theta_1 \\\\\n      \\theta_2\n  \\end{pmatrix}\\\\\n\\end{split} \n$$\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-5_21aa8da816a1b74245fd0bcee7046981'}\n\n```{.r .cell-code}\nX <- cbind(x1 = c(3,4,1,8,5),\n           x2 = c(100,140,200,70,270))\n(WX <-  W %*% X)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     x1  x2\n[1,]  6 105\n[2,]  3 190\n[3,]  6 105\n[4,]  3 190\n[5,]  6 105\n```\n:::\n:::\n\n\n\nThus, only direct neighbours -- as defined in ${\\bm W}$ -- contribute to those local spillover effects. The $\\hat{\\bm\\theta}$ coefficients only estimate how my direct neighbour's $\\bm X$ values influence my own outcome $\\bm y$.\n\nThere are no higher order neighbours involved (as long as we do not model them), nor are there any feedback loops due to interdependence.\n\n### Global spillovers\n\nIn contrast, spillover effects in SAR, SAC, and SDM models do not only include direct neighbours but also neighbours of neighbours (second order neighbours) and further higher-order neighbours. This can be seen by rewriting the inverse $({\\bm I_N}-\\rho {\\bm W})^{-1}$ as power series:A power series of $\\sum\\nolimits_{k=0}^\\infty {\\bm W}^k$ converges to $({\\bm I}-{\\bm W})^{-1}$ if the maximum absolute eigenvalue of ${\\bm W} < 1$, which is ensured by standardizing ${\\bm W}$.}\n\n$$\n\\begin{split}\n({\\bm I_N}-\\rho {\\bm W})^{-1}\\beta_k \n=({\\bm I_N} + \\rho{\\bm W} + \\rho^2{\\bm W}^2 + \\rho^3{\\bm W}^3 + ...)\\beta_k \n= ({\\bm I_N} + \\sum_{h=1}^\\infty \\rho^h{\\bm W}^h)\\beta_k ,\n\\end{split}\n$$\n\nwhere the identity matrix represents the direct effects and the sum represents the first and higher order indirect effects and the above mentioned feedback loops. This implies that a change in one unit $i$ does not only affect the direct neighbours but passes through the whole system towards higher-order neighbours, where the impact declines with distance within the neighbouring system. Global indirect impacts thus are `multiplied' by influencing direct neighbours as specified in $\\bm W$ and indirect neighbours not connected according to $\\bm W$, with additional feedback loops between those neighbours.\n\n$$\n\\begin{split}\n\\underbrace{(\\underbrace{\\bm I_N}_{N \\times N} - \\underbrace{\\rho}_{\\hat{=} 0.6} \\underbrace{\\bm W}_{N \\times N})^{-1}}_{N \\times N} \\beta_k\n&=\n\\begin{pmatrix}\n      1.\\color{red}{1875} & 0.46875 & 0.1875 & 0.46875 & 0.1875 \\\\\n      0.3125 & 1.\\color{red}{28125} & 0.3125 & 0.28125 & 0.3125 \\\\\n      0.1875 & 0.46875 & 1.\\color{red}{1875} & 0.46875 & 0.1875 \\\\\n      0.3125 & 0.28125 & 0.3125 & 1.\\color{red}{28125} & 0.3125 \\\\\n      0.1875 & 0.46875 & 0.1875 & 0.46875 & 1.\\color{red}{1875}\n      \\end{pmatrix}\n  \\begin{matrix}\n      (\\beta_1 + \\beta_2)\\\\\n  \\end{matrix}\\\\.\n\\end{split}\n$$\n\nAll diagonal elements of $\\mathrm{diag}({\\bm W})=w_{ii}=0$. However, diagonal elements of higher order neighbours are not zero $\\mathrm{diag}({\\bm W}^2)=\\mathrm{diag}({\\bm W}{\\bm W})\\neq0$. \n\nIntuitively, $\\rho{\\bm W}$ only represents the effects between direct neighbours (and the focal unit is not a neighbour of the focal unit itself), whereas $\\rho^2{\\bm W}^2$ contains the effects of second order neighbours, where the focal unit is a second order neighbour of the focal unit itself. Thus, $({\\bm I_N}-\\rho {\\bm W})^{-1}\\beta_k$ includes <span style=\"color:red\">feedback effects</span> from $\\rho^2{\\bm W}^2$ on (they are part of the direct impacts according to the summary measures below). This is way the <span style=\"color:red\">diagonal above</span> $\\geq 1$.\n\nIn consequence, local and global spillover effects represent two distinct kinds of spatial spillover effects [@LeSage.2014]. The interpretation of local spillover effects is straightforward: it represents the effect of all neighbours as defined by ${\\bm W}$ (the average over all neighbours in case of a row-normalised weights matrix). \n\nFor instance, the environmental quality in the focal unit itself but also in neighbouring units could influence the attractiveness of a district and its house prices. In this example it seems reasonable to assume that we have local spillover effects: only the environmental quality in directly contiguous units (e.g. in walking distance) is relevant for estimating the house prices. \n\nIn contrast, interpreting global spillover effects can be a bit more difficult. Intuitively, the global spillover effects can be seen as a kind of diffusion process. For example, an exogenous event might increase the house prices in one district of a city, thus leading to an adaptation of house prices in neighbouring districts, which then leads to further adaptations in other units (the neighbours of the neighbours), thereby globally diffusing the effect of the exogenous event due to the endogenous term. \n\nYet, those processes happen over time. In a cross-sectional framework, the global spillover effects are hard to interpret. @Anselin.2003 proposes an interpretation as an equilibrium outcome, where the partial impact represents an estimate of how this long-run equilibrium would change due to a change in ${\\bm x}_k$ [@LeSage.2014].\n\n\n\n## Summary impact measures\n\nNote that the derivative in SAR, SAC, and SDM is a $N \\times N$ matrix, returning individual effects of each unit on each other unit, differentiated in _direct, indirect, and total impacts_. \n\n$$\n\\begin{split}\n(\\bm I_N - \\rho \\bm W)^{-1} \\beta &=\n\\begin{pmatrix}\n      \\color{red}{1.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} \\\\\n      \\color{blue}{0.3125} & \\color{red}{1.28125} & \\color{blue}{0.3125} & \\color{blue}{0.28125} & \\color{blue}{0.3125} \\\\\n      \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{red}{1.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} \\\\\n      \\color{blue}{0.3125} & \\color{blue}{0.28125} & \\color{blue}{0.3125} & \\color{red}{1.28125} & \\color{blue}{0.3125} \\\\\n      \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{red}{1.1875}\n      \\end{pmatrix} \\beta\n\\end{split}\n$$\n\n**However, the individual effects (how $i$ influences $j$) mainly vary because of variation in ${\\bm W}$. **\n\n::: callout-warning\n### Do not interpret these as \"estimated\" individual impacts\n\nWe estimate two scalar parameters in a SAR model: $\\beta$ for the direct coefficient and $rho$ for the auto-regressive parameter.\n\nAll variation in the effects matrix $(\\bm I_N - \\rho \\bm W)^{-1}$ \\beta comes from the relationship in $\\bm W$ which we have given a-priori!\n:::\n\n\nSince reporting the individual partial effects is usually not of interest, @LeSage.2009 proposed to average over these effect matrices. While the average diagonal elements of the effects matrix $(\\bm I_N - \\rho \\bm W)^{-1}$ represent the so called direct impacts of variable ${\\bm x}_k$, the average column-sums of the off-diagonal elements represent the so called indirect impacts (or spatial spillover effects). \n\n<span style=\"color:red\">direct impacts</span> refer to an average effect of a unit change in $x_i$ on $y_i$, and <span style=\"color:blue\">the indirect (spillover) impacts</span>  indicate how a change in $x_i$, on average, influences all neighbouring units $y_j$.\n\nThough previous literature [@HalleckVega.2015; @LeSage.2009] has established the notation of direct and indirect impacts, it is important to note that also the direct impacts comprise a spatial `multiplier' component if we specify an endogenous lagged depended variable, as a change in $\\bm x_i$ influences $\\bm y_i$, which influences $\\bm y_j$, which in turn influences $\\bm y_i$.\n\n\nUsually, one should use summary measures to report effects in spatial models [@LeSage.2009]. @HalleckVega.2015 provide a nice summary of the impacts for each model:\n\n\nModel | Direct Impacts | Indirect Impacts | type\n:-: | :-: | :-: | :-:\nOLS/SEM | $\\beta_k$ | -- | --\nSAR/SAC | <span style=\"color:red\">Diagonal elements</span> of $({\\bm I}-\\rho{\\bm W})^{-1}\\beta_k$ | <span style=\"color:blue\">Off-diagonal elements</span>  of $({\\bm I}-\\rho{\\bm W})^{-1}\\beta_k$ | global\nSLX/SDEM | $\\beta_k$ | $\\theta_k$ | local\nSDM | <span style=\"color:red\">Diagonal elements</span>  of $({\\bm I}-\\rho{\\bm W})^{-1}\\left[\\beta_k+{\\bm W}\\theta_k\\right]$ | <span style=\"color:blue\">Off-diagonal elements</span> of $({\\bm I}-\\rho{\\bm W})^{-1}\\left[\\beta_k+{\\bm W}\\theta_k\\right]$ |global\n\n$$\n\\begin{split}\n(\\bm I_N - \\rho \\bm W)^{-1} \\beta &=\n\\begin{pmatrix}\n      \\color{red}{1.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} \\\\\n      \\color{blue}{0.3125} & \\color{red}{1.28125} & \\color{blue}{0.3125} & \\color{blue}{0.28125} & \\color{blue}{0.3125} \\\\\n      \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{red}{1.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} \\\\\n      \\color{blue}{0.3125} & \\color{blue}{0.28125} & \\color{blue}{0.3125} & \\color{red}{1.28125} & \\color{blue}{0.3125} \\\\\n      \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{blue}{0.1875} & \\color{blue}{0.46875} & \\color{red}{1.1875}\n      \\end{pmatrix} \\beta\n\\end{split}\n$$\n\nThe different indirect effects / spatial effects mean conceptually different things:\n\n* Global spillover effects: SAR, SAC, SDM\n\n* Local spillover effects: SLX, SDEM\n\n::: callout-warning\n### Common ratio between direct and indirect impacts in SAR and SAC\n\nNote that impacts in SAR only estimate one single spatial multiplier coefficient. Thus direct and indirect impacts are bound to a common ratio, say $\\phi$, across all covariates.\n\nif $\\beta_1^{direct} = \\phi\\beta_1^{indirect}$, then $\\beta_2^{direct} = \\phi\\beta_2^{indirect}$, $\\beta_k^{direct} = \\phi\\beta_k^{indirect}$. \n:::\n\nWe can calculate these impacts using `impacts()` with simulated distributions, e.g. for the SAR model:\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-6_bbb736f64c5656868491860d8aa7ab39'}\n\n```{.r .cell-code}\nmod_1.sar.imp <- impacts(mod_1.sar, listw = queens.lw, R = 300)\nsummary(mod_1.sar.imp, zstats = TRUE, short = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nImpact measures (lag, exact):\n                  Direct     Indirect        Total\nlog(no2)     0.447853184  0.754466618  1.202319802\nlog(POPDEN) -0.062973027 -0.106086209 -0.169059236\nper_mixed    0.020884672  0.035182931  0.056067603\nper_asian   -0.002575602 -0.004338934 -0.006914536\nper_black   -0.014253206 -0.024011369 -0.038264575\nper_other   -0.001820705 -0.003067212 -0.004887917\n========================================================\nSimulation results ( variance matrix):\n========================================================\nSimulated standard errors\n                  Direct     Indirect       Total\nlog(no2)    0.0488746577 0.0992947679 0.135731528\nlog(POPDEN) 0.0138348654 0.0272604116 0.040219045\nper_mixed   0.0062340535 0.0114284286 0.017423600\nper_asian   0.0005028114 0.0008278141 0.001282866\nper_black   0.0009584477 0.0022958909 0.002660797\nper_other   0.0032087463 0.0055369935 0.008732728\n\nSimulated z-values:\n                 Direct    Indirect       Total\nlog(no2)      9.1699338   7.6050769   8.8654548\nlog(POPDEN)  -4.6050047  -3.9594280  -4.2677606\nper_mixed     3.3619039   3.1048256   3.2393746\nper_asian    -5.1308747  -5.2313286  -5.3867117\nper_black   -14.9323624 -10.4988735 -14.4378407\nper_other    -0.5277511  -0.5269264  -0.5280146\n\nSimulated p-values:\n            Direct     Indirect   Total     \nlog(no2)    < 2.22e-16 2.8422e-14 < 2.22e-16\nlog(POPDEN) 4.1246e-06 7.5129e-05 1.9745e-05\nper_mixed   0.00077407 0.0019039  0.0011979 \nper_asian   2.8840e-07 1.6830e-07 7.1758e-08\nper_black   < 2.22e-16 < 2.22e-16 < 2.22e-16\nper_other   0.59767208 0.5982447  0.5974892 \n```\n:::\n\n```{.r .cell-code}\n# Alternative with traces (better for large W)\nW <- as(queens.lw, \"CsparseMatrix\")\ntrMatc <- trW(W, type = \"mult\",\n              m = 30) # number of powers\nmod_1.sar.imp2 <- impacts(mod_1.sar, \n                          tr = trMatc, # trace instead of listw\n                          R = 300, \n                          Q = 30) # number of power series used for approximation\nsummary(mod_1.sar.imp2, zstats = TRUE, short = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nImpact measures (lag, trace):\n                  Direct     Indirect        Total\nlog(no2)     0.447853101  0.754459497  1.202312598\nlog(POPDEN) -0.062973015 -0.106085208 -0.169058223\nper_mixed    0.020884668  0.035182599  0.056067267\nper_asian   -0.002575601 -0.004338893 -0.006914494\nper_black   -0.014253203 -0.024011142 -0.038264346\nper_other   -0.001820704 -0.003067183 -0.004887888\n========================================================\nSimulation results ( variance matrix):\n========================================================\nSimulated standard errors\n                 Direct     Indirect       Total\nlog(no2)    0.047110308 0.0924219350 0.127555773\nlog(POPDEN) 0.014335172 0.0268662539 0.040458337\nper_mixed   0.006676480 0.0117103841 0.018188023\nper_asian   0.000509860 0.0008152945 0.001284136\nper_black   0.001050298 0.0022327528 0.002762871\nper_other   0.003306380 0.0056900174 0.008981326\n\nSimulated z-values:\n                 Direct    Indirect       Total\nlog(no2)      9.5292084   8.1928725   9.4556683\nlog(POPDEN)  -4.4094068  -3.9827415  -4.2070673\nper_mixed     3.1382280   3.0241420   3.0990824\nper_asian    -5.0011138  -5.2515590  -5.3198684\nper_black   -13.5952749 -10.7839159 -13.8829882\nper_other    -0.5551403  -0.5562902  -0.5568004\n\nSimulated p-values:\n            Direct     Indirect   Total     \nlog(no2)    < 2.22e-16 2.2204e-16 < 2.22e-16\nlog(POPDEN) 1.0365e-05 6.8125e-05 2.5871e-05\nper_mixed   0.0016997  0.0024934  0.0019412 \nper_asian   5.7000e-07 1.5082e-07 1.0384e-07\nper_black   < 2.22e-16 < 2.22e-16 < 2.22e-16\nper_other   0.5787987  0.5780125  0.5776638 \n```\n:::\n:::\n\n\n\nThe indirect effects in SAR, SAC, and SDM refer to global spillover effects. This means a change of $x$ in the focal units flows through the entire system of neighbours (direct nieightbours, neighbours of neighbours, ...) influencing 'their $y$'. One can think of this as diffusion or a change in a long-term equilibrium.\n\n_If Log NO2 increases by one unit, this increases the house price in the focal unit by 0.448 units. Overall, a one unit change in log NO2 increases the house prices in the entire neighbourhood system (direct and higher order neighbours) by  0.754._\n\nFor SLX models, nothing is gained from computing the impacts, as they equal the coefficients. Again, it's the effects of direct neighbours only.\n\n\n\n::: {.cell hash='07_impacts_cache/pdf/unnamed-chunk-7_cc6887717dc7208e5d996cf8bd5da1f4'}\n\n```{.r .cell-code}\nprint(impacts(mod_1.slx, listw = queens.lw))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nImpact measures (SlX, glht):\n                  Direct     Indirect        Total\nlog(no2)    -0.440727458  0.993602103  0.552874645\nlog(POPDEN) -0.076839828  0.113262218  0.036422390\nper_mixed   -0.033042221  0.126068686  0.093026466\nper_asian   -0.002380698 -0.003828126 -0.006208824\nper_black   -0.016229407 -0.018053503 -0.034282910\nper_other   -0.020391354  0.048139008  0.027747654\n```\n:::\n:::\n\n\n\n\n\n## Examples\n\n### @Boillat.2022  {.unnumbered}\n\n_The paper investigates the effects of protected areas and various land tenure regimes on deforestation and possible spillover effects in Bolivia, a global tropical deforestation hotspot._\n\n![](fig/Boillat.png)\n\n_Protected areas – which in Bolivia are all based on co-management schemes - also protect forests in adjacent areas, showing an indirect protective spillover effect. Indigenous lands however only have direct forest protection effects._\n\n### @Fischer.2009  {.unnumbered}\n\n_The focus of this paper is on the role of human capital in explaining labor productivity variation among 198 European regions within a regression framework._\n\n![](fig/Fischer.png)\n\n_A ceteris paribus increase in the level of human capital is found to have a significant and positive direct impact. But this positive direct impact is offset by a significant and negative indirect (spillover) impact leading to a total impact that is not significantly different from zero._\n\n_The intuition here arises from the notion that it is relative regional advantages in human capital that matter most for labor productivity, so changing human capital across all regions should have little or no total impact on (average) labor productivity levels._\n\n### @Ruttenauer.2018a  {.unnumbered}\n\n_This study investigates the presence of environmental inequality in Germany - the connection between the presence of foreign-minority population and objectively measured industrial pollution._\n\n![](fig/census.png)\n\n_Results reveal that the share of minorities within a census cell indeed positively correlates with the exposure to industrial pollution. Furthermore, spatial spillover effects are highly relevant: the characteristics of the neighbouring spatial units matter in predicting the amount of pollution. Especially within urban areas, clusters of high minority neighbourhoods are affected by high levels of environmental pollution._\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}