<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Geodata &amp; Spatial Regression - 7&nbsp; Spatial Impacts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08_exercise1.html" rel="next">
<link href="./06_regression-estimation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07_impacts.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial Impacts</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Geodata &amp; Spatial Regression</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ruettenauer/Geodata_Spatial_Regression/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Refresher</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Manipulation &amp; Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_weights.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial Relationships W</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_dependence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Detecting Spatial Dependence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_regression-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial Regression Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_regression-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatial Regression Models: Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_impacts.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial Impacts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_exercise1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exercise I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Comparing and Selecting Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_spatiotemporal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatio-temporal models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Other Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_exercise2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exercise II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#required-packages" id="toc-required-packages" class="nav-link active" data-scroll-target="#required-packages">Required packages</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session info</a></li>
  <li><a href="#reload-data-from-pervious-session" id="toc-reload-data-from-pervious-session" class="nav-link" data-scroll-target="#reload-data-from-pervious-session">Reload data from pervious session</a></li>
  <li><a href="#coefficient-estimates-neq-marginal-effects" id="toc-coefficient-estimates-neq-marginal-effects" class="nav-link" data-scroll-target="#coefficient-estimates-neq-marginal-effects"><span class="header-section-number">7.1</span> Coefficient estimates <span class="math inline">\(\neq\)</span> `marginal’ effects</a></li>
  <li><a href="#global-and-local-spillovers" id="toc-global-and-local-spillovers" class="nav-link" data-scroll-target="#global-and-local-spillovers"><span class="header-section-number">7.2</span> Global and local spillovers</a>
  <ul class="collapse">
  <li><a href="#local-spillovers" id="toc-local-spillovers" class="nav-link" data-scroll-target="#local-spillovers"><span class="header-section-number">7.2.1</span> Local spillovers</a></li>
  <li><a href="#global-spillovers" id="toc-global-spillovers" class="nav-link" data-scroll-target="#global-spillovers"><span class="header-section-number">7.2.2</span> Global spillovers</a></li>
  </ul></li>
  <li><a href="#summary-impact-measures" id="toc-summary-impact-measures" class="nav-link" data-scroll-target="#summary-impact-measures"><span class="header-section-number">7.3</span> Summary impact measures</a></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"><span class="header-section-number">7.4</span> Examples</a>
  <ul class="collapse">
  <li><a href="#boillat.2022" id="toc-boillat.2022" class="nav-link" data-scroll-target="#boillat.2022"><span class="citation" data-cites="Boillat.2022">Boillat, Ceddia, and Bottazzi (2022)</span></a></li>
  <li><a href="#fischer.2009" id="toc-fischer.2009" class="nav-link" data-scroll-target="#fischer.2009"><span class="citation" data-cites="Fischer.2009">Fischer et al. (2009)</span></a></li>
  <li><a href="#ruttenauer.2018a" id="toc-ruttenauer.2018a" class="nav-link" data-scroll-target="#ruttenauer.2018a"><span class="citation" data-cites="Ruttenauer.2018a">Rüttenauer (2018)</span></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial Impacts</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="required-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="required-packages">Required packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sf"</span>, <span class="st">"mapview"</span>, <span class="st">"spdep"</span>, <span class="st">"spatialreg"</span>, <span class="st">"tmap"</span>, <span class="st">"viridisLite"</span>) <span class="co"># note: load spdep first, then spatialreg</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(pkgs, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="session-info" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="session-info">Session info</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] viridisLite_0.4.2 tmap_3.3-3        spatialreg_1.2-9 
[4] Matrix_1.5-4.1    spdep_1.2-8       spData_2.2.2     
[7] mapview_2.11.0    sf_1.0-13        

loaded via a namespace (and not attached):
 [1] xfun_0.39          raster_3.6-20      htmlwidgets_1.6.2 
 [4] lattice_0.21-8     vctrs_0.6.3        tools_4.3.1       
 [7] crosstalk_1.2.0    LearnBayes_2.15.1  generics_0.1.3    
[10] parallel_4.3.1     stats4_4.3.1       sandwich_3.0-2    
[13] tibble_3.2.1       proxy_0.4-27       fansi_1.0.4       
[16] pkgconfig_2.0.3    KernSmooth_2.23-21 satellite_1.0.4   
[19] RColorBrewer_1.1-3 leaflet_2.1.2      webshot_0.5.4     
[22] lifecycle_1.0.3    compiler_4.3.1     deldir_1.0-9      
[25] munsell_0.5.0      terra_1.7-29       leafsync_0.1.0    
[28] codetools_0.2-19   stars_0.6-1        htmltools_0.5.5   
[31] class_7.3-22       pillar_1.9.0       MASS_7.3-60       
[34] classInt_0.4-9     lwgeom_0.2-13      wk_0.7.3          
[37] abind_1.4-5        boot_1.3-28.1      multcomp_1.4-24   
[40] nlme_3.1-162       tidyselect_1.2.0   digest_0.6.31     
[43] mvtnorm_1.2-2      dplyr_1.1.2        splines_4.3.1     
[46] fastmap_1.1.1      grid_4.3.1         colorspace_2.1-0  
[49] expm_0.999-7       cli_3.6.1          magrittr_2.0.3    
[52] base64enc_0.1-3    dichromat_2.0-0.1  XML_3.99-0.14     
[55] survival_3.5-5     utf8_1.2.3         TH.data_1.1-2     
[58] leafem_0.2.0       e1071_1.7-13       scales_1.2.1      
[61] sp_1.6-1           rmarkdown_2.22     zoo_1.8-12        
[64] png_0.1-8          coda_0.19-4        evaluate_0.21     
[67] knitr_1.43         tmaptools_3.1-1    s2_1.1.4          
[70] rlang_1.1.1        Rcpp_1.0.10        glue_1.6.2        
[73] DBI_1.1.3          jsonlite_1.8.5     R6_2.5.1          
[76] units_0.8-2       </code></pre>
</div>
</div>
</section>
<section id="reload-data-from-pervious-session" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="reload-data-from-pervious-session">Reload data from pervious session</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"_data/msoa2_spatial.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="coefficient-estimates-neq-marginal-effects" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="coefficient-estimates-neq-marginal-effects"><span class="header-section-number">7.1</span> Coefficient estimates <span class="math inline">\(\neq\)</span> `marginal’ effects</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do not interpret coefficients as marginal effects in SAR, SAC, and SDM!!</p>
</div>
</div>
<p>At first glance, the specifications presented above seem relatively similar in the way of modelling spatial effects. <strong>Yet, they differ in very important aspects</strong>.</p>
<p>First, models with an endogenous spatial term (SAR, SAC, and SDM) assume a very different spatial dependence structure than models with only exogenous spatial terms as SLX and SDEM specifications. While the first three assume <strong>global</strong> spatial dependence, the second two assume <strong>local</strong> spatial dependence <span class="citation" data-cites="Anselin.2003 HalleckVega.2015 LeSage.2009">(<a href="references.html#ref-Anselin.2003" role="doc-biblioref">Anselin 2003</a>; <a href="references.html#ref-HalleckVega.2015" role="doc-biblioref">Halleck Vega and Elhorst 2015</a>; <a href="references.html#ref-LeSage.2009" role="doc-biblioref">LeSage and Pace 2009</a>)</span>.</p>
<p>Second, the interpretation of the coefficients differs greatly between models with and without endogenous effects. This becomes apparent when considering the reduced form of the equations above. Exemplary using the SAR model, the reduced form is given by:</p>
<p><span class="math display">\[
{\boldsymbol{\mathbf{y}}}-\rho{\boldsymbol{\mathbf{W}}}{\boldsymbol{\mathbf{y}}} ={\boldsymbol{\mathbf{X}}}{\boldsymbol{\mathbf{\beta}}}+ {\boldsymbol{\mathbf{\varepsilon}}}, \nonumber \\
({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}}){\boldsymbol{\mathbf{y}}}={\boldsymbol{\mathbf{X}}}{\boldsymbol{\mathbf{\beta}}}+ {\boldsymbol{\mathbf{\varepsilon}}}\nonumber, \\
{\boldsymbol{\mathbf{y}}} =({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}({\boldsymbol{\mathbf{X}}}{\boldsymbol{\mathbf{\beta}}}+ {\boldsymbol{\mathbf{\varepsilon}}}),
\]</span> where <span class="math inline">\({\boldsymbol{\mathbf{I}}_N}\)</span> is an <span class="math inline">\(N \times N\)</span> diagonal matrix (diagonal elements equal 1, 0 otherwise). This contains no spatially lagged dependent variable on the right-hand side.</p>
<p>If we want to interpret coefficient, we are usually in marginal or partial effects (the association between a unit change in <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>). We obtain these effects by looking at the first derivative.</p>
<p>When taking the first derivative of the explanatory variable <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> from the reduced form in (<span class="math inline">\(\ref{eq:sarred}\)</span>) to interpret the partial effect of a unit change in variable <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> on <span class="math inline">\({\boldsymbol{\mathbf{y}}}\)</span>, we receive</p>
<p><span class="math display">\[
\frac{\partial {\boldsymbol{\mathbf{y}}}}{\partial {\boldsymbol{\mathbf{x}}}_k}=\underbrace{({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}}_{N \times N}\beta_k,
\]</span></p>
<p>for each covariate <span class="math inline">\(k=\{1,2,...,K\}\)</span>. As can be seen, the partial derivative with respect to <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> produces an <span class="math inline">\(N \times N\)</span> matrix, thereby representing the partial effect of each unit <span class="math inline">\(i\)</span> onto the focal unit <span class="math inline">\(i\)</span> itself and all other units .</p>
<p>Note that the diagonal elements of <span class="math inline">\(({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}\)</span> are not zero anymore (as they are in <span class="math inline">\(\boldsymbol{\mathbf{W}}\)</span>). Look at the following minimal example:</p>
<p><span class="math display">\[
\begin{split}
\tilde{\boldsymbol{\mathbf{W}}} = \begin{pmatrix}
      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0 \\
      1 &amp; 0 &amp; 1 &amp; 0 &amp; 1 \\
      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0 \\
      1 &amp; 0 &amp; 1 &amp; 0 &amp; 1 \\
      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0
      \end{pmatrix}, \mathrm{and~normalized} ~
\boldsymbol{\mathbf{W}} = \begin{pmatrix}
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 \\
      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 \\
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 \\
      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 \\
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0
      \end{pmatrix}      
\end{split}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\rho = 0.6,
\]</span></p>
<p>then</p>
<p><span class="math display">\[
\begin{split}
\rho \boldsymbol{\mathbf{W}} = \begin{pmatrix}
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 \\
      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 \\
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 \\
      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 \\
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0
      \end{pmatrix}.
\end{split}
\]</span></p>
<p>If we want to get the total effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> we need to add the direct association wihtin <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> and so on…</p>
<p><span class="math display">\[
\begin{split}
\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}} &amp;=
\begin{pmatrix}
      1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
      0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 \\
      0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 \\
      0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 \\
      0 &amp; 1 &amp; 0 &amp; 0 &amp; 1
      \end{pmatrix} -
\begin{pmatrix}
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 \\
      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 \\
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 \\
      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 \\
      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0
      \end{pmatrix}\\
&amp; = \begin{pmatrix}
      1 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 0 \\
      -0.2 &amp; 1 &amp; -0.2 &amp; 0 &amp; -0.2 \\
      0 &amp; 0.3 &amp; 1 &amp; 0.3 &amp; 0 \\
      -0.2 &amp; 0 &amp; -0.2 &amp; 1 &amp; -0.2 \\
      0 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 1
      \end{pmatrix}.
\end{split}
\]</span></p>
<p>And finally we take the inverse of that</p>
<p><span class="math display">\[
\begin{split}
(\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1} &amp;=
\begin{pmatrix}
      1 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 0 \\
      -0.2 &amp; 1 &amp; -0.2 &amp; 0 &amp; -0.2 \\
      0 &amp; 0.3 &amp; 1 &amp; 0.3 &amp; 0 \\
      -0.2 &amp; 0 &amp; -0.2 &amp; 1 &amp; -0.2 \\
      0 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 1
      \end{pmatrix}^{-1}\\
&amp;=
\begin{pmatrix}
      \color{red}{1.1875} &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; \color{red}{1.28125} &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; \color{red}{1.1875} &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; \color{red}{1.28125} &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; \color{red}{1.1875}
      \end{pmatrix}.
\end{split}
\]</span></p>
<p>As you can see, <span class="math inline">\((\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1}\)</span> has <span class="math inline">\(&gt;1\)</span>: these are feedback loops. My <span class="math inline">\(X\)</span> influences my <span class="math inline">\(Y\)</span> directly, but my <span class="math inline">\(Y\)</span> then influences my neigbour’s <span class="math inline">\(Y\)</span>, which then influences my <span class="math inline">\(Y\)</span> again (also also other neighbour’s <span class="math inline">\(Y\)</span>s). Thus the influence of my <span class="math inline">\(X\)</span> on my <span class="math inline">\(Y\)</span> includes a spatial multiplier.</p>
<p>Check yourself:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>I <span class="ot">=</span> <span class="fu">diag</span>(<span class="dv">5</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">=</span> <span class="fl">0.6</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>W <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>(<span class="at">IrW =</span> I <span class="sc">-</span> rho<span class="sc">*</span>W)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5]
[1,]  1.0 -0.3  0.0 -0.3  0.0
[2,] -0.2  1.0 -0.2  0.0 -0.2
[3,]  0.0 -0.3  1.0 -0.3  0.0
[4,] -0.2  0.0 -0.2  1.0 -0.2
[5,]  0.0 -0.3  0.0 -0.3  1.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (I - rho*W)^-1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">M =</span> <span class="fu">solve</span>(IrW))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]    [,2]   [,3]    [,4]   [,5]
[1,] 1.1875 0.46875 0.1875 0.46875 0.1875
[2,] 0.3125 1.28125 0.3125 0.28125 0.3125
[3,] 0.1875 0.46875 1.1875 0.46875 0.1875
[4,] 0.3125 0.28125 0.3125 1.28125 0.3125
[5,] 0.1875 0.46875 0.1875 0.46875 1.1875</code></pre>
</div>
</div>
<p>The diagonal elements of indicate how each unit <span class="math inline">\(i\)</span> influences itself (change of <span class="math inline">\(x_i\)</span> on change of <span class="math inline">\(y_i\)</span>), and each off-diagonal elements in column <span class="math inline">\(j\)</span> represents the effect of <span class="math inline">\(j\)</span> on each other unit <span class="math inline">\(i\)</span> (change of <span class="math inline">\(x_j\)</span> on change of <span class="math inline">\(y_i\)</span>).</p>
<p><span class="math display">\[
\begin{split}
\begin{pmatrix}
      1.1875 &amp; \color{red}{0.46875} &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; 1.28125 &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; 1.1875 &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; 1.28125 &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; \color{blue}{0.1875} &amp; 0.46875 &amp; 1.1875
      \end{pmatrix}.
\end{split}
\]</span></p>
<p>For instance, <span class="math inline">\(\color{red}{W_{12}}\)</span> indicates that unit 2 has an influence of 0.46875 on unit 1. On the other hand, <span class="math inline">\(\color{blue}{W_{53}}\)</span> indicates that unit 3 has an influence of magnitude 0.1875 on unit 5.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why does unit 3 have any effect o unit 5? According to <span class="math inline">\(\boldsymbol{\mathbf{W}}\)</span> those two units are no neighbours <span class="math inline">\(w_{53} = 0\)</span>!</p>
</div>
</div>
<!-- $$  -->
<!--    \begin{equation} -->
<!--    \begin{split} -->
<!--        {\bm y} & =\alpha{\bm \iota}+\rho {\bm W}{\bm y}+{\bm X}{\bm \beta}+{\bm \varepsilon} \\ -->
<!--        {\bm y} & =({\bm I}-\rho{\bm W})^{-1}(\alpha{\bm \iota}+{\bm X}{\bm \beta}+{\bm \varepsilon}), -->
<!--    \end{split} -->
<!--    \end{equation} -->
<!-- $$  -->
<!-- we can calculate the first derivative: -->
<!-- $$  -->
<!--    \begin{equation} -->
<!--    \begin{split} -->
<!--        \frac{\partial \bm y}{\partial \bm x_k} & = ({\bm I}-\rho{\bm W})^{-1}\beta_k \\ -->
<!--        & =({\bm I} + \rho{\bm W} + \rho^2{\bm W}^2 + \rho^3{\bm W}^3 + ...)\beta_k,  -->
<!--    \end{split} -->
<!--    \end{equation}   -->
<!-- $$  -->
<!--    where $\rho{\bm W}\beta_k$ equals the effect stemming from direct neighbours, $\rho^2{\bm W}^2\beta_k$ the effect stemming from second order neighbours (neighbours of neighbours),...  -->
<!-- for SAR, SAC, and SDM even the direct impacts differ from the point estimates. This results from the fact that an endogenous term of the dependent variable ${\bm W}{\bm y}$ contains feedback loops through the system of neighbours \citep{Betz.2019,Franzese.2007.0,HalleckVega.2015.0}. A change of $x_{i}$ in the focal unit $i$ influences the focal unit $i$ itself, but also the neighbouring unit $j$, which in turn influences the focal unit $i$ in a feedback loop. This feedback loop is part of the direct impact. -->
</section>
<section id="global-and-local-spillovers" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="global-and-local-spillovers"><span class="header-section-number">7.2</span> Global and local spillovers</h2>
<p>The kind of indirect spillover effects in SAR, SAC, and SDM models differs from the kind of indirect spillover effects in SLX and SDEM models: while the first three specifications represent <strong>global spillover effects</strong>, the latter three represent <strong>local spillover effects</strong> <span class="citation" data-cites="Anselin.2003 LeSage.2009 LeSage.2014">(<a href="references.html#ref-Anselin.2003" role="doc-biblioref">Anselin 2003</a>; <a href="references.html#ref-LeSage.2009" role="doc-biblioref">LeSage and Pace 2009</a>; <a href="references.html#ref-LeSage.2014" role="doc-biblioref">LeSage 2014</a>)</span>.</p>
<section id="local-spillovers" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="local-spillovers"><span class="header-section-number">7.2.1</span> Local spillovers</h3>
<p>In case of SLX and SDEM the spatial spillover effects can be interpreted as the effect of a one unit change of <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> in the spatially weighted neighbouring observations on the dependent variable of the focal unit: the weighted average among neighbours; when using a row-normalised contiguity weights matrix, <span class="math inline">\({\boldsymbol{\mathbf{W}}} {\boldsymbol{\mathbf{x}}}_k\)</span> is the mean value of <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> in the neighbouring units.</p>
<p>Assume we have <span class="math inline">\(k =2\)</span> covariates, then</p>
<p><span class="math display">\[
\begin{split}
\underbrace{\boldsymbol{\mathbf{W}}}_{N \times N}  \underbrace{\boldsymbol{\mathbf{X}}}_{N \times 2} \underbrace{\boldsymbol{\mathbf{\theta}}}_{2 \times 1} &amp; =
\begin{pmatrix}
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 \\
      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 \\
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 \\
      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 \\
      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0
  \end{pmatrix}
  \begin{pmatrix}
      3 &amp; 100 \\
      4 &amp; 140 \\
      1 &amp; 200 \\
      7 &amp; 70  \\
      5 &amp; 250
  \end{pmatrix}
    \begin{pmatrix}
      \theta_1 \\
      \theta_2
  \end{pmatrix}\\
&amp; =   
\begin{pmatrix}
      6 &amp; 105 \\
      3 &amp; 190 \\
      6 &amp; 105 \\
      3 &amp; 190  \\
      6 &amp; 105
  \end{pmatrix}
\begin{pmatrix}
      \theta_1 \\
      \theta_2
  \end{pmatrix}\\
\end{split}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">x1 =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">8</span>,<span class="dv">5</span>),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">x2 =</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">140</span>,<span class="dv">200</span>,<span class="dv">70</span>,<span class="dv">270</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>(WX <span class="ot">&lt;-</span>  W <span class="sc">%*%</span> X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     x1  x2
[1,]  6 105
[2,]  3 190
[3,]  6 105
[4,]  3 190
[5,]  6 105</code></pre>
</div>
</div>
<p>Thus, only direct neighbours – as defined in <span class="math inline">\({\boldsymbol{\mathbf{W}}}\)</span> – contribute to those local spillover effects. The <span class="math inline">\(\hat{\boldsymbol{\mathbf{\theta}}}\)</span> coefficients only estimate how my direct neighbour’s <span class="math inline">\(\boldsymbol{\mathbf{X}}\)</span> values influence my own outcome <span class="math inline">\(\boldsymbol{\mathbf{y}}\)</span>.</p>
<p>There are no higher order neighbours involved (as long as we do not model them), nor are there any feedback loops due to interdependence.</p>
</section>
<section id="global-spillovers" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="global-spillovers"><span class="header-section-number">7.2.2</span> Global spillovers</h3>
<p>In contrast, spillover effects in SAR, SAC, and SDM models do not only include direct neighbours but also neighbours of neighbours (second order neighbours) and further higher-order neighbours. This can be seen by rewriting the inverse <span class="math inline">\(({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}\)</span> as power series:A power series of <span class="math inline">\(\sum\nolimits_{k=0}^\infty {\boldsymbol{\mathbf{W}}}^k\)</span> converges to <span class="math inline">\(({\boldsymbol{\mathbf{I}}}-{\boldsymbol{\mathbf{W}}})^{-1}\)</span> if the maximum absolute eigenvalue of <span class="math inline">\({\boldsymbol{\mathbf{W}}} &lt; 1\)</span>, which is ensured by standardizing <span class="math inline">\({\boldsymbol{\mathbf{W}}}\)</span>.}</p>
<p><span class="math display">\[
\begin{split}
({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}\beta_k
=({\boldsymbol{\mathbf{I}}_N} + \rho{\boldsymbol{\mathbf{W}}} + \rho^2{\boldsymbol{\mathbf{W}}}^2 + \rho^3{\boldsymbol{\mathbf{W}}}^3 + ...)\beta_k
= ({\boldsymbol{\mathbf{I}}_N} + \sum_{h=1}^\infty \rho^h{\boldsymbol{\mathbf{W}}}^h)\beta_k ,
\end{split}
\]</span></p>
<p>where the identity matrix represents the direct effects and the sum represents the first and higher order indirect effects and the above mentioned feedback loops. This implies that a change in one unit <span class="math inline">\(i\)</span> does not only affect the direct neighbours but passes through the whole system towards higher-order neighbours, where the impact declines with distance within the neighbouring system. Global indirect impacts thus are `multiplied’ by influencing direct neighbours as specified in <span class="math inline">\(\boldsymbol{\mathbf{W}}\)</span> and indirect neighbours not connected according to <span class="math inline">\(\boldsymbol{\mathbf{W}}\)</span>, with additional feedback loops between those neighbours.</p>
<p><span class="math display">\[
\begin{split}
\underbrace{(\underbrace{\boldsymbol{\mathbf{I}}_N}_{N \times N} - \underbrace{\rho}_{\hat{=} 0.6} \underbrace{\boldsymbol{\mathbf{W}}}_{N \times N})^{-1}}_{N \times N} \beta_k
&amp;=
\begin{pmatrix}
      1.\color{red}{1875} &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; 1.\color{red}{28125} &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; 1.\color{red}{1875} &amp; 0.46875 &amp; 0.1875 \\
      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; 1.\color{red}{28125} &amp; 0.3125 \\
      0.1875 &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 1.\color{red}{1875}
      \end{pmatrix}
  \begin{matrix}
      (\beta_1 + \beta_2)\\
  \end{matrix}\\.
\end{split}
\]</span></p>
<p>All diagonal elements of <span class="math inline">\(\mathrm{diag}({\boldsymbol{\mathbf{W}}})=w_{ii}=0\)</span>. However, diagonal elements of higher order neighbours are not zero <span class="math inline">\(\mathrm{diag}({\boldsymbol{\mathbf{W}}}^2)=\mathrm{diag}({\boldsymbol{\mathbf{W}}}{\boldsymbol{\mathbf{W}}})\neq0\)</span>.</p>
<p>Intuitively, <span class="math inline">\(\rho{\boldsymbol{\mathbf{W}}}\)</span> only represents the effects between direct neighbours (and the focal unit is not a neighbour of the focal unit itself), whereas <span class="math inline">\(\rho^2{\boldsymbol{\mathbf{W}}}^2\)</span> contains the effects of second order neighbours, where the focal unit is a second order neighbour of the focal unit itself. Thus, <span class="math inline">\(({\boldsymbol{\mathbf{I}}_N}-\rho {\boldsymbol{\mathbf{W}}})^{-1}\beta_k\)</span> includes <span style="color:red">feedback effects</span> from <span class="math inline">\(\rho^2{\boldsymbol{\mathbf{W}}}^2\)</span> on (they are part of the direct impacts according to the summary measures below). This is way the <span style="color:red">diagonal above</span> <span class="math inline">\(\geq 1\)</span>.</p>
<p>In consequence, local and global spillover effects represent two distinct kinds of spatial spillover effects <span class="citation" data-cites="LeSage.2014">(<a href="references.html#ref-LeSage.2014" role="doc-biblioref">LeSage 2014</a>)</span>. The interpretation of local spillover effects is straightforward: it represents the effect of all neighbours as defined by <span class="math inline">\({\boldsymbol{\mathbf{W}}}\)</span> (the average over all neighbours in case of a row-normalised weights matrix).</p>
<p>For instance, the environmental quality in the focal unit itself but also in neighbouring units could influence the attractiveness of a district and its house prices. In this example it seems reasonable to assume that we have local spillover effects: only the environmental quality in directly contiguous units (e.g.&nbsp;in walking distance) is relevant for estimating the house prices.</p>
<p>In contrast, interpreting global spillover effects can be a bit more difficult. Intuitively, the global spillover effects can be seen as a kind of diffusion process. For example, an exogenous event might increase the house prices in one district of a city, thus leading to an adaptation of house prices in neighbouring districts, which then leads to further adaptations in other units (the neighbours of the neighbours), thereby globally diffusing the effect of the exogenous event due to the endogenous term.</p>
<p>Yet, those processes happen over time. In a cross-sectional framework, the global spillover effects are hard to interpret. <span class="citation" data-cites="Anselin.2003">Anselin (<a href="references.html#ref-Anselin.2003" role="doc-biblioref">2003</a>)</span> proposes an interpretation as an equilibrium outcome, where the partial impact represents an estimate of how this long-run equilibrium would change due to a change in <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span> <span class="citation" data-cites="LeSage.2014">(<a href="references.html#ref-LeSage.2014" role="doc-biblioref">LeSage 2014</a>)</span>.</p>
</section>
</section>
<section id="summary-impact-measures" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="summary-impact-measures"><span class="header-section-number">7.3</span> Summary impact measures</h2>
<p>Note that the derivative in SAR, SAC, and SDM is a <span class="math inline">\(N \times N\)</span> matrix, returning individual effects of each unit on each other unit, differentiated in <em>direct, indirect, and total impacts</em>.</p>
<p><span class="math display">\[
\begin{split}
(\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1} \beta &amp;=
\begin{pmatrix}
      \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} \\
      \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} \\
      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} \\
      \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} \\
      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875}
      \end{pmatrix} \beta
\end{split}
\]</span></p>
<p><strong>However, the individual effects (how <span class="math inline">\(i\)</span> influences <span class="math inline">\(j\)</span>) mainly vary because of variation in <span class="math inline">\({\boldsymbol{\mathbf{W}}}\)</span>. </strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Do not interpret these as “estimated” individual impacts
</div>
</div>
<div class="callout-body-container callout-body">
<p>We estimate two scalar parameters in a SAR model: <span class="math inline">\(\beta\)</span> for the direct coefficient and <span class="math inline">\(rho\)</span> for the auto-regressive parameter.</p>
<p>All variation in the effects matrix <span class="math inline">\((\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1}\)</span> comes from the relationship in <span class="math inline">\(\boldsymbol{\mathbf{W}}\)</span> which we have given a-priori!</p>
</div>
</div>
<p>Since reporting the individual partial effects is usually not of interest, <span class="citation" data-cites="LeSage.2009">LeSage and Pace (<a href="references.html#ref-LeSage.2009" role="doc-biblioref">2009</a>)</span> proposed to average over these effect matrices. While the average diagonal elements of the effects matrix <span class="math inline">\((\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1}\)</span> represent the so called direct impacts of variable <span class="math inline">\({\boldsymbol{\mathbf{x}}}_k\)</span>, the average column-sums of the off-diagonal elements represent the so called indirect impacts (or spatial spillover effects).</p>
<p><span style="color:red">direct impacts</span> refer to an average effect of a unit change in <span class="math inline">\(x_i\)</span> on <span class="math inline">\(y_i\)</span>, and <span style="color:blue">the indirect (spillover) impacts</span> indicate how a change in <span class="math inline">\(x_i\)</span>, on average, influences all neighbouring units <span class="math inline">\(y_j\)</span>.</p>
<p>Though previous literature <span class="citation" data-cites="HalleckVega.2015 LeSage.2009">(<a href="references.html#ref-HalleckVega.2015" role="doc-biblioref">Halleck Vega and Elhorst 2015</a>; <a href="references.html#ref-LeSage.2009" role="doc-biblioref">LeSage and Pace 2009</a>)</span> has established the notation of direct and indirect impacts, it is important to note that also the direct impacts comprise a spatial `multiplier’ component if we specify an endogenous lagged depended variable, as a change in <span class="math inline">\(\boldsymbol{\mathbf{x}}_i\)</span> influences <span class="math inline">\(\boldsymbol{\mathbf{y}}_i\)</span>, which influences <span class="math inline">\(\boldsymbol{\mathbf{y}}_j\)</span>, which in turn influences <span class="math inline">\(\boldsymbol{\mathbf{y}}_i\)</span>.</p>
<p>Usually, one should use summary measures to report effects in spatial models <span class="citation" data-cites="LeSage.2009">(<a href="references.html#ref-LeSage.2009" role="doc-biblioref">LeSage and Pace 2009</a>)</span>. <span class="citation" data-cites="HalleckVega.2015">Halleck Vega and Elhorst (<a href="references.html#ref-HalleckVega.2015" role="doc-biblioref">2015</a>)</span> provide a nice summary of the impacts for each model:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Model</th>
<th style="text-align: center;">Direct Impacts</th>
<th style="text-align: center;">Indirect Impacts</th>
<th style="text-align: center;">type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">OLS/SEM</td>
<td style="text-align: center;"><span class="math inline">\(\beta_k\)</span></td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">–</td>
</tr>
<tr class="even">
<td style="text-align: center;">SAR/SAC</td>
<td style="text-align: center;"><span style="color:red">Diagonal elements</span> of <span class="math inline">\(({\boldsymbol{\mathbf{I}}}-\rho{\boldsymbol{\mathbf{W}}})^{-1}\beta_k\)</span></td>
<td style="text-align: center;"><span style="color:blue">Off-diagonal elements</span> of <span class="math inline">\(({\boldsymbol{\mathbf{I}}}-\rho{\boldsymbol{\mathbf{W}}})^{-1}\beta_k\)</span></td>
<td style="text-align: center;">global</td>
</tr>
<tr class="odd">
<td style="text-align: center;">SLX/SDEM</td>
<td style="text-align: center;"><span class="math inline">\(\beta_k\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\theta_k\)</span></td>
<td style="text-align: center;">local</td>
</tr>
<tr class="even">
<td style="text-align: center;">SDM</td>
<td style="text-align: center;"><span style="color:red">Diagonal elements</span> of <span class="math inline">\(({\boldsymbol{\mathbf{I}}}-\rho{\boldsymbol{\mathbf{W}}})^{-1}\left[\beta_k+{\boldsymbol{\mathbf{W}}}\theta_k\right]\)</span></td>
<td style="text-align: center;"><span style="color:blue">Off-diagonal elements</span> of <span class="math inline">\(({\boldsymbol{\mathbf{I}}}-\rho{\boldsymbol{\mathbf{W}}})^{-1}\)</span></td>
<td style="text-align: center;">global</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{split}
(\boldsymbol{\mathbf{I}}_N - \rho \boldsymbol{\mathbf{W}})^{-1} \beta &amp;=
\begin{pmatrix}
      \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} \\
      \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} \\
      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} \\
      \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} \\
      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875}
      \end{pmatrix} \beta
\end{split}
\]</span></p>
<p>The different indirect effects / spatial effects mean conceptually different things:</p>
<ul>
<li><p>Global spillover effects: SAR, SAC, SDM</p></li>
<li><p>Local spillover effects: SLX, SDEM</p></li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Common ratio between direct and indirect impacts in SAR and SAC
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that impacts in SAR only estimate one single spatial multiplier coefficient. Thus direct and indirect impacts are bound to a common ratio, say <span class="math inline">\(\phi\)</span>, across all covariates.</p>
<p>if <span class="math inline">\(\beta_1^{direct} = \phi\beta_1^{indirect}\)</span>, then <span class="math inline">\(\beta_2^{direct} = \phi\beta_2^{indirect}\)</span>, <span class="math inline">\(\beta_k^{direct} = \phi\beta_k^{indirect}\)</span>.</p>
</div>
</div>
<p>We can calculate these impacts using <code>impacts()</code> with simulated distributions, e.g.&nbsp;for the SAR model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod_1.sar.imp <span class="ot">&lt;-</span> <span class="fu">impacts</span>(mod_1.sar, <span class="at">listw =</span> queens.lw, <span class="at">R =</span> <span class="dv">300</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_1.sar.imp, <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, exact):
                  Direct     Indirect        Total
log(no2)     0.447853184  0.754466618  1.202319802
log(POPDEN) -0.062973027 -0.106086209 -0.169059236
per_mixed    0.020884672  0.035182931  0.056067603
per_asian   -0.002575602 -0.004338934 -0.006914536
per_black   -0.014253206 -0.024011369 -0.038264575
per_other   -0.001820705 -0.003067212 -0.004887917
========================================================
Simulation results ( variance matrix):
========================================================
Simulated standard errors
                  Direct     Indirect       Total
log(no2)    0.0490902204 0.0991887277 0.136963307
log(POPDEN) 0.0136300762 0.0269172501 0.039785922
per_mixed   0.0068017371 0.0119807712 0.018551571
per_asian   0.0005056667 0.0008589735 0.001320154
per_black   0.0010458877 0.0021616572 0.002625838
per_other   0.0030679673 0.0053011809 0.008354446

Simulated z-values:
                 Direct    Indirect       Total
log(no2)      9.1318719   7.6660763   8.8248012
log(POPDEN)  -4.6168953  -3.9851631  -4.2778515
per_mixed     3.0830744   2.9728234   3.0502527
per_asian    -5.1785329  -5.1588845  -5.3402547
per_black   -13.6541960 -11.1953696 -14.6548698
per_other    -0.6977937  -0.6958632  -0.6977967

Simulated p-values:
            Direct     Indirect   Total     
log(no2)    &lt; 2.22e-16 1.7764e-14 &lt; 2.22e-16
log(POPDEN) 3.8952e-06 6.7434e-05 1.8871e-05
per_mixed   0.0020487  0.0029507  0.0022865 
per_asian   2.2364e-07 2.4843e-07 9.2816e-08
per_black   &lt; 2.22e-16 &lt; 2.22e-16 &lt; 2.22e-16
per_other   0.4853062  0.4865145  0.4853043 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative with traces (better for large W)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as</span>(queens.lw, <span class="st">"CsparseMatrix"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>trMatc <span class="ot">&lt;-</span> <span class="fu">trW</span>(W, <span class="at">type =</span> <span class="st">"mult"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">m =</span> <span class="dv">30</span>) <span class="co"># number of powers</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>mod_1.sar.imp2 <span class="ot">&lt;-</span> <span class="fu">impacts</span>(mod_1.sar, </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tr =</span> trMatc, <span class="co"># trace instead of listw</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">R =</span> <span class="dv">300</span>, </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Q =</span> <span class="dv">30</span>) <span class="co"># number of power series used for approximation</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_1.sar.imp2, <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, trace):
                  Direct     Indirect        Total
log(no2)     0.447853101  0.754459497  1.202312598
log(POPDEN) -0.062973015 -0.106085208 -0.169058223
per_mixed    0.020884668  0.035182599  0.056067267
per_asian   -0.002575601 -0.004338893 -0.006914494
per_black   -0.014253203 -0.024011142 -0.038264346
per_other   -0.001820704 -0.003067183 -0.004887888
========================================================
Simulation results ( variance matrix):
========================================================
Simulated standard errors
                  Direct     Indirect       Total
log(no2)    0.0466689476 0.0883062136 0.122061548
log(POPDEN) 0.0136401631 0.0255808621 0.038346540
per_mixed   0.0063038790 0.0114117298 0.017510364
per_asian   0.0005275083 0.0008582116 0.001345567
per_black   0.0010108224 0.0023023773 0.002816746
per_other   0.0033540767 0.0057514393 0.009090367

Simulated z-values:
                 Direct    Indirect       Total
log(no2)      9.7028447   8.6245945   9.9492990
log(POPDEN)  -4.7529540  -4.2766445  -4.5435996
per_mixed     3.3089997   3.0899756   3.2050447
per_asian    -4.9015099  -5.0538505  -5.1449387
per_black   -14.1099152 -10.4264504 -13.5859746
per_other    -0.4297319  -0.4353042  -0.4339736

Simulated p-values:
            Direct     Indirect   Total     
log(no2)    &lt; 2.22e-16 &lt; 2.22e-16 &lt; 2.22e-16
log(POPDEN) 2.0047e-06 1.8973e-05 5.5302e-06
per_mixed   0.0009363  0.0020017  0.0013504 
per_asian   9.5103e-07 4.3299e-07 2.6761e-07
per_black   &lt; 2.22e-16 &lt; 2.22e-16 &lt; 2.22e-16
per_other   0.6673907  0.6633417  0.6643076 </code></pre>
</div>
</div>
<p>The indirect effects in SAR, SAC, and SDM refer to global spillover effects. This means a change of <span class="math inline">\(x\)</span> in the focal units flows through the entire system of neighbours (direct nieightbours, neighbours of neighbours, …) influencing ‘their <span class="math inline">\(y\)</span>’. One can think of this as diffusion or a change in a long-term equilibrium.</p>
<p><em>If population density increases by one unit, this increases the house price in the focal unit by 0.448 units. Overall, a one unit change in population density increases the house prices in the entire neighbourhood system (direct and higher order neighbours) by 0.754.</em></p>
<p>For SLX models, nothing is gained from computing the impacts, as they equal the coefficients. Again, it’s the effects of direct neighbours only.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">impacts</span>(mod_1.slx, <span class="at">listw =</span> queens.lw))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (SlX, glht):
                  Direct     Indirect        Total
log(no2)    -0.440727458  0.993602103  0.552874645
log(POPDEN) -0.076839828  0.113262218  0.036422390
per_mixed   -0.033042221  0.126068686  0.093026466
per_asian   -0.002380698 -0.003828126 -0.006208824
per_black   -0.016229407 -0.018053503 -0.034282910
per_other   -0.020391354  0.048139008  0.027747654</code></pre>
</div>
</div>
</section>
<section id="examples" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="examples"><span class="header-section-number">7.4</span> Examples</h2>
<section id="boillat.2022" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="boillat.2022"><span class="citation" data-cites="Boillat.2022">Boillat, Ceddia, and Bottazzi (<a href="references.html#ref-Boillat.2022" role="doc-biblioref">2022</a>)</span></h3>
<p><em>The paper investigates the effects of protected areas and various land tenure regimes on deforestation and possible spillover effects in Bolivia, a global tropical deforestation hotspot.</em></p>
<p><img src="fig/Boillat.png" class="img-fluid"></p>
<p><em>Protected areas – which in Bolivia are all based on co-management schemes - also protect forests in adjacent areas, showing an indirect protective spillover effect. Indigenous lands however only have direct forest protection effects.</em></p>
</section>
<section id="fischer.2009" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fischer.2009"><span class="citation" data-cites="Fischer.2009">Fischer et al. (<a href="references.html#ref-Fischer.2009" role="doc-biblioref">2009</a>)</span></h3>
<p><em>The focus of this paper is on the role of human capital in explaining labor productivity variation among 198 European regions within a regression framework.</em></p>
<p><img src="fig/Fischer.png" class="img-fluid"></p>
<p><em>A ceteris paribus increase in the level of human capital is found to have a significant and positive direct impact. But this positive direct impact is offset by a significant and negative indirect (spillover) impact leading to a total impact that is not significantly different from zero.</em></p>
<p><em>The intuition here arises from the notion that it is relative regional advantages in human capital that matter most for labor productivity, so changing human capital across all regions should have little or no total impact on (average) labor productivity levels.</em></p>
</section>
<section id="ruttenauer.2018a" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ruttenauer.2018a"><span class="citation" data-cites="Ruttenauer.2018a">Rüttenauer (<a href="references.html#ref-Ruttenauer.2018a" role="doc-biblioref">2018</a>)</span></h3>
<p><em>This study investigates the presence of environmental inequality in Germany - the connection between the presence of foreign-minority population and objectively measured industrial pollution.</em></p>
<p><img src="fig/census.png" class="img-fluid"></p>
<p><em>Results reveal that the share of minorities within a census cell indeed positively correlates with the exposure to industrial pollution. Furthermore, spatial spillover effects are highly relevant: the characteristics of the neighbouring spatial units matter in predicting the amount of pollution. Especially within urban areas, clusters of high minority neighbourhoods are affected by high levels of environmental pollution.</em></p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Anselin.2003" class="csl-entry" role="listitem">
Anselin, Luc. 2003. <span>“Spatial <span>Externalities</span>, <span>Spatial Multipliers</span>, and <span>Spatial Econometrics</span>.”</span> <em>International Regional Science Review</em> 26 (2): 153–66. <a href="https://doi.org/10.1177/0160017602250972">https://doi.org/10.1177/0160017602250972</a>.
</div>
<div id="ref-Boillat.2022" class="csl-entry" role="listitem">
Boillat, Sébastien, M. Graziano Ceddia, and Patrick Bottazzi. 2022. <span>“The Role of Protected Areas and Land Tenure Regimes on Forest Loss in <span>Bolivia</span>: <span>Accounting</span> for Spatial Spillovers.”</span> <em>Global Environmental Change</em> 76 (September): 102571. <a href="https://doi.org/10.1016/j.gloenvcha.2022.102571">https://doi.org/10.1016/j.gloenvcha.2022.102571</a>.
</div>
<div id="ref-Fischer.2009" class="csl-entry" role="listitem">
Fischer, Manfred M., Monika Bartkowska, Aleksandra Riedl, Sascha Sardadvar, and Andrea Kunnert. 2009. <span>“The Impact of Human Capital on Regional Labor Productivity in <span>Europe</span>.”</span> <em>Letters in Spatial and Resource Sciences</em> 2 (2-3): 97–108. <a href="https://doi.org/10.1007/s12076-009-0027-7">https://doi.org/10.1007/s12076-009-0027-7</a>.
</div>
<div id="ref-HalleckVega.2015" class="csl-entry" role="listitem">
Halleck Vega, Solmaria, and J. Paul Elhorst. 2015. <span>“The <span>SLX Model</span>.”</span> <em>Journal of Regional Science</em> 55 (3): 339–63. <a href="https://doi.org/10.1111/jors.12188">https://doi.org/10.1111/jors.12188</a>.
</div>
<div id="ref-LeSage.2014" class="csl-entry" role="listitem">
LeSage, James P. 2014. <span>“What <span>Regional Scientists Need</span> to <span>Know</span> about <span>Spatial Econometrics</span>.”</span> <em>The Review of Regional Studies</em> 44 (1): 13–32. https://doi.org/<a href="https://dx.doi.org/10.2139/ssrn.2420725">https://dx.doi.org/10.2139/ssrn.2420725</a>.
</div>
<div id="ref-LeSage.2009" class="csl-entry" role="listitem">
LeSage, James P., and R. Kelley Pace. 2009. <em>Introduction to <span>Spatial Econometrics</span></em>. Statistics, <span>Textbooks</span> and <span>Monographs</span>. <span>Boca Raton</span>: <span>CRC Press</span>.
</div>
<div id="ref-Ruttenauer.2018a" class="csl-entry" role="listitem">
Rüttenauer, Tobias. 2018. <span>“Neighbours <span>Matter</span>: <span class="nocase">A Nation-wide Small-area Assessment</span> of <span>Environmental Inequality</span> in <span>Germany</span>.”</span> <em>Social Science Research</em> 70: 198–211. <a href="https://doi.org/10.1016/j.ssresearch.2017.11.009">https://doi.org/10.1016/j.ssresearch.2017.11.009</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06_regression-estimation.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatial Regression Models: Estimation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08_exercise1.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exercise I</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb17" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>\newcommand{\Exp}{\mathrm{E}}</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>\newcommand\given<span class="co">[</span><span class="ot">1</span><span class="co">][]</span>{\:#1\vert\:}</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>\newcommand{\Cov}{\mathrm{Cov}}</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>\newcommand{\Var}{\mathrm{Var}}</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>\newcommand{\rank}{\mathrm{rank}}</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>\newcommand{\bm}<span class="co">[</span><span class="ot">1</span><span class="co">]</span>{\boldsymbol{\mathbf{#1}}}</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu"># Spatial Impacts</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">### Required packages {.unnumbered}</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message = FALSE, warning = FALSE, results = 'hide'}</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sf"</span>, <span class="st">"mapview"</span>, <span class="st">"spdep"</span>, <span class="st">"spatialreg"</span>, <span class="st">"tmap"</span>, <span class="st">"viridisLite"</span>) <span class="co"># note: load spdep first, then spatialreg</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(pkgs, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="fu">### Session info {.unnumbered}</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="fu">### Reload data from pervious session {.unnumbered}</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"_data/msoa2_spatial.RData"</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression-results, echo=FALSE}</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Contiguity (Queens) neighbours weights</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>queens.nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(msoa.spdf, </span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>                     <span class="at">queen =</span> <span class="cn">TRUE</span>, </span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>                     <span class="at">snap =</span> <span class="dv">1</span>) <span class="co"># we consider points in 1m distance as 'touching'</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>queens.lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(queens.nb,</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>                      <span class="at">style =</span> <span class="st">"W"</span>)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>mod_1.sar <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(<span class="fu">log</span>(med_house_price) <span class="sc">~</span> <span class="fu">log</span>(no2) <span class="sc">+</span> <span class="fu">log</span>(POPDEN) <span class="sc">+</span> </span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>                        per_mixed <span class="sc">+</span> per_asian <span class="sc">+</span> per_black <span class="sc">+</span> per_other,  </span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> msoa.spdf, </span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>                     <span class="at">listw =</span> queens.lw,</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>                     <span class="at">Durbin =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>mod_1.sem <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(<span class="fu">log</span>(med_house_price) <span class="sc">~</span> <span class="fu">log</span>(no2) <span class="sc">+</span> <span class="fu">log</span>(POPDEN) <span class="sc">+</span> </span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>                        per_mixed <span class="sc">+</span> per_asian <span class="sc">+</span> per_black <span class="sc">+</span> per_other,  </span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> msoa.spdf, </span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>                     <span class="at">listw =</span> queens.lw,</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>                     <span class="at">Durbin =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>mod_1.slx <span class="ot">&lt;-</span> <span class="fu">lmSLX</span>(<span class="fu">log</span>(med_house_price) <span class="sc">~</span> <span class="fu">log</span>(no2) <span class="sc">+</span> <span class="fu">log</span>(POPDEN) <span class="sc">+</span> </span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>                        per_mixed <span class="sc">+</span> per_asian <span class="sc">+</span> per_black <span class="sc">+</span> per_other, </span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> msoa.spdf, </span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>                  <span class="at">listw =</span> queens.lw, </span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Durbin =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## Coefficient estimates $\neq$ `marginal' effects</span></span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a>Do not interpret coefficients as marginal effects in SAR, SAC, and SDM!! </span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a>At first glance, the specifications presented above seem relatively similar in the way of modelling spatial effects. **Yet, they differ in very important aspects**. </span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a>First, models with an endogenous spatial term (SAR, SAC, and SDM) assume a very different spatial dependence structure than models with only exogenous spatial terms as SLX and SDEM specifications. While the first three assume **global** spatial dependence, the second two assume **local** spatial dependence <span class="co">[</span><span class="ot">@Anselin.2003; @HalleckVega.2015; @LeSage.2009</span><span class="co">]</span>. </span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a>Second, the interpretation of the coefficients differs greatly between models with and without endogenous effects. This becomes apparent when considering the reduced form of the equations above. Exemplary using the SAR model, the reduced form is given by:</span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a>{\bm y}-\rho{\bm W}{\bm y} ={\bm X}{\bm \beta}+ {\bm \varepsilon}, \nonumber <span class="sc">\\</span></span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a>({\bm I_N}-\rho {\bm W}){\bm y}={\bm X}{\bm \beta}+ {\bm \varepsilon}\nonumber, <span class="sc">\\</span></span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a>{\bm y} =({\bm I_N}-\rho {\bm W})^{-1}({\bm X}{\bm \beta}+ {\bm \varepsilon}),</span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a>where ${\bm I_N}$ is an $N \times N$ diagonal matrix (diagonal elements equal 1, 0 otherwise). This contains no spatially lagged dependent variable on the right-hand side.</span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a>If we want to interpret coefficient, we are usually in marginal or partial effects (the association between a unit change in $X$ and $Y$). We obtain these effects by looking at the first derivative.</span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a>When taking the first derivative of the explanatory variable ${\bm x}_k$ from the reduced form in (\ref{eq:sarred}) to interpret the partial effect of a unit change in variable ${\bm x}_k$ on ${\bm y}$, we receive</span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a>\frac{\partial {\bm y}}{\partial {\bm x}_k}=\underbrace{({\bm I_N}-\rho {\bm W})^{-1}}_{N \times N}\beta_k,</span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a>for each covariate $k=<span class="sc">\{</span>1,2,...,K<span class="sc">\}</span>$. As can be seen, the partial derivative with respect to ${\bm x}_k$ produces an $N \times N$ matrix, thereby representing the partial effect of each unit $i$ onto the focal unit $i$ itself and all other units \textcolor{red}{$j=<span class="sc">\{</span>1,2,...,i-1,i+1,...,N<span class="sc">\}</span>$}. </span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a>Note that the diagonal elements of $({\bm I_N}-\rho {\bm W})^{-1}$ are not zero anymore (as they are in $\bm W$). Look at the following minimal example:</span>
<span id="cb17-96"><a href="#cb17-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-97"><a href="#cb17-97" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-98"><a href="#cb17-98" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-99"><a href="#cb17-99" aria-hidden="true" tabindex="-1"></a>\tilde{\bm W} = \begin{pmatrix}</span>
<span id="cb17-100"><a href="#cb17-100" aria-hidden="true" tabindex="-1"></a>      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-101"><a href="#cb17-101" aria-hidden="true" tabindex="-1"></a>      1 &amp; 0 &amp; 1 &amp; 0 &amp; 1 <span class="sc">\\</span></span>
<span id="cb17-102"><a href="#cb17-102" aria-hidden="true" tabindex="-1"></a>      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-103"><a href="#cb17-103" aria-hidden="true" tabindex="-1"></a>      1 &amp; 0 &amp; 1 &amp; 0 &amp; 1 <span class="sc">\\</span></span>
<span id="cb17-104"><a href="#cb17-104" aria-hidden="true" tabindex="-1"></a>      0 &amp; 1 &amp; 0 &amp; 1 &amp; 0</span>
<span id="cb17-105"><a href="#cb17-105" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}, \mathrm{and~normalized} ~</span>
<span id="cb17-106"><a href="#cb17-106" aria-hidden="true" tabindex="-1"></a>\bm W = \begin{pmatrix}</span>
<span id="cb17-107"><a href="#cb17-107" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-108"><a href="#cb17-108" aria-hidden="true" tabindex="-1"></a>      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 <span class="sc">\\</span></span>
<span id="cb17-109"><a href="#cb17-109" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-110"><a href="#cb17-110" aria-hidden="true" tabindex="-1"></a>      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 <span class="sc">\\</span></span>
<span id="cb17-111"><a href="#cb17-111" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0</span>
<span id="cb17-112"><a href="#cb17-112" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}      </span>
<span id="cb17-113"><a href="#cb17-113" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-114"><a href="#cb17-114" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-115"><a href="#cb17-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-116"><a href="#cb17-116" aria-hidden="true" tabindex="-1"></a>and </span>
<span id="cb17-117"><a href="#cb17-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-118"><a href="#cb17-118" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-119"><a href="#cb17-119" aria-hidden="true" tabindex="-1"></a>\rho = 0.6,</span>
<span id="cb17-120"><a href="#cb17-120" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-121"><a href="#cb17-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-122"><a href="#cb17-122" aria-hidden="true" tabindex="-1"></a>then </span>
<span id="cb17-123"><a href="#cb17-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-124"><a href="#cb17-124" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-125"><a href="#cb17-125" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-126"><a href="#cb17-126" aria-hidden="true" tabindex="-1"></a>\rho \bm W = \begin{pmatrix}</span>
<span id="cb17-127"><a href="#cb17-127" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-128"><a href="#cb17-128" aria-hidden="true" tabindex="-1"></a>      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 <span class="sc">\\</span></span>
<span id="cb17-129"><a href="#cb17-129" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-130"><a href="#cb17-130" aria-hidden="true" tabindex="-1"></a>      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 <span class="sc">\\</span></span>
<span id="cb17-131"><a href="#cb17-131" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0</span>
<span id="cb17-132"><a href="#cb17-132" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}.</span>
<span id="cb17-133"><a href="#cb17-133" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-134"><a href="#cb17-134" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-135"><a href="#cb17-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-136"><a href="#cb17-136" aria-hidden="true" tabindex="-1"></a>If we want to get the total effect of $X$ on $Y$ we need to add the direct association wihtin $i$ and $j$ and so on... </span>
<span id="cb17-137"><a href="#cb17-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-138"><a href="#cb17-138" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-139"><a href="#cb17-139" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-140"><a href="#cb17-140" aria-hidden="true" tabindex="-1"></a>\bm I_N - \rho \bm W &amp;=</span>
<span id="cb17-141"><a href="#cb17-141" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-142"><a href="#cb17-142" aria-hidden="true" tabindex="-1"></a>      1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-143"><a href="#cb17-143" aria-hidden="true" tabindex="-1"></a>      0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-144"><a href="#cb17-144" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-145"><a href="#cb17-145" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-146"><a href="#cb17-146" aria-hidden="true" tabindex="-1"></a>      0 &amp; 1 &amp; 0 &amp; 0 &amp; 1</span>
<span id="cb17-147"><a href="#cb17-147" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix} - </span>
<span id="cb17-148"><a href="#cb17-148" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-149"><a href="#cb17-149" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-150"><a href="#cb17-150" aria-hidden="true" tabindex="-1"></a>      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 <span class="sc">\\</span></span>
<span id="cb17-151"><a href="#cb17-151" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-152"><a href="#cb17-152" aria-hidden="true" tabindex="-1"></a>      0.2 &amp; 0 &amp; 0.2 &amp; 0 &amp; 0.2 <span class="sc">\\</span></span>
<span id="cb17-153"><a href="#cb17-153" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 0 &amp; 0.3 &amp; 0</span>
<span id="cb17-154"><a href="#cb17-154" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}<span class="sc">\\</span></span>
<span id="cb17-155"><a href="#cb17-155" aria-hidden="true" tabindex="-1"></a>&amp; = \begin{pmatrix}</span>
<span id="cb17-156"><a href="#cb17-156" aria-hidden="true" tabindex="-1"></a>      1 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-157"><a href="#cb17-157" aria-hidden="true" tabindex="-1"></a>      -0.2 &amp; 1 &amp; -0.2 &amp; 0 &amp; -0.2 <span class="sc">\\</span></span>
<span id="cb17-158"><a href="#cb17-158" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 1 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-159"><a href="#cb17-159" aria-hidden="true" tabindex="-1"></a>      -0.2 &amp; 0 &amp; -0.2 &amp; 1 &amp; -0.2 <span class="sc">\\</span></span>
<span id="cb17-160"><a href="#cb17-160" aria-hidden="true" tabindex="-1"></a>      0 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 1</span>
<span id="cb17-161"><a href="#cb17-161" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}.</span>
<span id="cb17-162"><a href="#cb17-162" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-163"><a href="#cb17-163" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-164"><a href="#cb17-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-165"><a href="#cb17-165" aria-hidden="true" tabindex="-1"></a>And finally we take the inverse of that</span>
<span id="cb17-166"><a href="#cb17-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-167"><a href="#cb17-167" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-168"><a href="#cb17-168" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-169"><a href="#cb17-169" aria-hidden="true" tabindex="-1"></a>(\bm I_N - \rho \bm W)^{-1} &amp;=</span>
<span id="cb17-170"><a href="#cb17-170" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-171"><a href="#cb17-171" aria-hidden="true" tabindex="-1"></a>      1 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-172"><a href="#cb17-172" aria-hidden="true" tabindex="-1"></a>      -0.2 &amp; 1 &amp; -0.2 &amp; 0 &amp; -0.2 <span class="sc">\\</span></span>
<span id="cb17-173"><a href="#cb17-173" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.3 &amp; 1 &amp; 0.3 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-174"><a href="#cb17-174" aria-hidden="true" tabindex="-1"></a>      -0.2 &amp; 0 &amp; -0.2 &amp; 1 &amp; -0.2 <span class="sc">\\</span></span>
<span id="cb17-175"><a href="#cb17-175" aria-hidden="true" tabindex="-1"></a>      0 &amp; -0.3 &amp; 0 &amp; -0.3 &amp; 1</span>
<span id="cb17-176"><a href="#cb17-176" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}^{-1}<span class="sc">\\</span></span>
<span id="cb17-177"><a href="#cb17-177" aria-hidden="true" tabindex="-1"></a>&amp;=</span>
<span id="cb17-178"><a href="#cb17-178" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-179"><a href="#cb17-179" aria-hidden="true" tabindex="-1"></a>      \color{red}{1.1875} &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-180"><a href="#cb17-180" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; \color{red}{1.28125} &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-181"><a href="#cb17-181" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; \color{red}{1.1875} &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-182"><a href="#cb17-182" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; \color{red}{1.28125} &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-183"><a href="#cb17-183" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; \color{red}{1.1875}</span>
<span id="cb17-184"><a href="#cb17-184" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}.</span>
<span id="cb17-185"><a href="#cb17-185" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-186"><a href="#cb17-186" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-187"><a href="#cb17-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-188"><a href="#cb17-188" aria-hidden="true" tabindex="-1"></a>As you can see, $(\bm I_N - \rho \bm W)^{-1}$ has \color{red}{diagonal elements} $&gt;1$: these are feedback loops. My $X$ influences my $Y$ directly, but my $Y$ then influences my neigbour's $Y$, which then influences my $Y$ again (also also other neighbour's $Y$s). Thus the influence of my $X$ on my $Y$ includes a spatial multiplier.</span>
<span id="cb17-189"><a href="#cb17-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-190"><a href="#cb17-190" aria-hidden="true" tabindex="-1"></a>Check yourself:</span>
<span id="cb17-191"><a href="#cb17-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-194"><a href="#cb17-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-195"><a href="#cb17-195" aria-hidden="true" tabindex="-1"></a>I <span class="ot">=</span> <span class="fu">diag</span>(<span class="dv">5</span>)</span>
<span id="cb17-196"><a href="#cb17-196" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">=</span> <span class="fl">0.6</span></span>
<span id="cb17-197"><a href="#cb17-197" aria-hidden="true" tabindex="-1"></a>W <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>,</span>
<span id="cb17-198"><a href="#cb17-198" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb17-199"><a href="#cb17-199" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>,</span>
<span id="cb17-200"><a href="#cb17-200" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> , <span class="dv">0</span> , <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb17-201"><a href="#cb17-201" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span> , <span class="fl">0.5</span> , <span class="dv">0</span>), <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-202"><a href="#cb17-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-203"><a href="#cb17-203" aria-hidden="true" tabindex="-1"></a>(<span class="at">IrW =</span> I <span class="sc">-</span> rho<span class="sc">*</span>W)</span>
<span id="cb17-204"><a href="#cb17-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-205"><a href="#cb17-205" aria-hidden="true" tabindex="-1"></a><span class="co"># (I - rho*W)^-1</span></span>
<span id="cb17-206"><a href="#cb17-206" aria-hidden="true" tabindex="-1"></a>(<span class="at">M =</span> <span class="fu">solve</span>(IrW))</span>
<span id="cb17-207"><a href="#cb17-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-208"><a href="#cb17-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-209"><a href="#cb17-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-210"><a href="#cb17-210" aria-hidden="true" tabindex="-1"></a>The diagonal elements of indicate how each unit $i$ influences itself (change of $x_i$ on change of $y_i$), and each off-diagonal elements in column $j$ represents the effect of $j$ on each other unit $i$ (change of $x_j$ on change of $y_i$). </span>
<span id="cb17-211"><a href="#cb17-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-212"><a href="#cb17-212" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-213"><a href="#cb17-213" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-214"><a href="#cb17-214" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-215"><a href="#cb17-215" aria-hidden="true" tabindex="-1"></a>      1.1875 &amp; \color{red}{0.46875} &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-216"><a href="#cb17-216" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; 1.28125 &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-217"><a href="#cb17-217" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; 1.1875 &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-218"><a href="#cb17-218" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; 1.28125 &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-219"><a href="#cb17-219" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; \color{blue}{0.1875} &amp; 0.46875 &amp; 1.1875</span>
<span id="cb17-220"><a href="#cb17-220" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}.</span>
<span id="cb17-221"><a href="#cb17-221" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-222"><a href="#cb17-222" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-223"><a href="#cb17-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-224"><a href="#cb17-224" aria-hidden="true" tabindex="-1"></a>For instance, $\color{red}{W_{12}}$ indicates that unit 2 has an influence of 0.46875 on unit 1. On the other hand, $\color{blue}{W_{53}}$ indicates that unit 3 has an influence of magnitude 0.1875 on unit 5.</span>
<span id="cb17-225"><a href="#cb17-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-226"><a href="#cb17-226" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb17-227"><a href="#cb17-227" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question</span></span>
<span id="cb17-228"><a href="#cb17-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-229"><a href="#cb17-229" aria-hidden="true" tabindex="-1"></a>Why does unit 3 have any effect o unit 5? According to $\bm W$ those two units are no neighbours $w_{53} = 0$!</span>
<span id="cb17-230"><a href="#cb17-230" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-231"><a href="#cb17-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-232"><a href="#cb17-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-233"><a href="#cb17-233" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$  --&gt;</span></span>
<span id="cb17-234"><a href="#cb17-234" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \begin{equation} --&gt;</span></span>
<span id="cb17-235"><a href="#cb17-235" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \begin{split} --&gt;</span></span>
<span id="cb17-236"><a href="#cb17-236" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--        {\bm y} &amp; =\alpha{\bm \iota}+\rho {\bm W}{\bm y}+{\bm X}{\bm \beta}+{\bm \varepsilon} \\ --&gt;</span></span>
<span id="cb17-237"><a href="#cb17-237" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--        {\bm y} &amp; =({\bm I}-\rho{\bm W})^{-1}(\alpha{\bm \iota}+{\bm X}{\bm \beta}+{\bm \varepsilon}), --&gt;</span></span>
<span id="cb17-238"><a href="#cb17-238" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \end{split} --&gt;</span></span>
<span id="cb17-239"><a href="#cb17-239" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \end{equation} --&gt;</span></span>
<span id="cb17-240"><a href="#cb17-240" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$  --&gt;</span></span>
<span id="cb17-241"><a href="#cb17-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-242"><a href="#cb17-242" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- we can calculate the first derivative: --&gt;</span></span>
<span id="cb17-243"><a href="#cb17-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-244"><a href="#cb17-244" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$  --&gt;</span></span>
<span id="cb17-245"><a href="#cb17-245" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \begin{equation} --&gt;</span></span>
<span id="cb17-246"><a href="#cb17-246" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \begin{split} --&gt;</span></span>
<span id="cb17-247"><a href="#cb17-247" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--        \frac{\partial \bm y}{\partial \bm x_k} &amp; = ({\bm I}-\rho{\bm W})^{-1}\beta_k \\ --&gt;</span></span>
<span id="cb17-248"><a href="#cb17-248" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--        &amp; =({\bm I} + \rho{\bm W} + \rho^2{\bm W}^2 + \rho^3{\bm W}^3 + ...)\beta_k,  --&gt;</span></span>
<span id="cb17-249"><a href="#cb17-249" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \end{split} --&gt;</span></span>
<span id="cb17-250"><a href="#cb17-250" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    \end{equation}   --&gt;</span></span>
<span id="cb17-251"><a href="#cb17-251" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$  --&gt;</span></span>
<span id="cb17-252"><a href="#cb17-252" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--    where $\rho{\bm W}\beta_k$ equals the effect stemming from direct neighbours, $\rho^2{\bm W}^2\beta_k$ the effect stemming from second order neighbours (neighbours of neighbours),...  --&gt;</span></span>
<span id="cb17-253"><a href="#cb17-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-254"><a href="#cb17-254" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- for SAR, SAC, and SDM even the direct impacts differ from the point estimates. This results from the fact that an endogenous term of the dependent variable ${\bm W}{\bm y}$ contains feedback loops through the system of neighbours \citep{Betz.2019,Franzese.2007.0,HalleckVega.2015.0}. A change of $x_{i}$ in the focal unit $i$ influences the focal unit $i$ itself, but also the neighbouring unit $j$, which in turn influences the focal unit $i$ in a feedback loop. This feedback loop is part of the direct impact. --&gt;</span></span>
<span id="cb17-255"><a href="#cb17-255" aria-hidden="true" tabindex="-1"></a><span class="in">    </span></span>
<span id="cb17-256"><a href="#cb17-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## Global and local spillovers</span></span>
<span id="cb17-257"><a href="#cb17-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-258"><a href="#cb17-258" aria-hidden="true" tabindex="-1"></a>The kind of indirect spillover effects in SAR, SAC, and SDM models differs from the kind of indirect spillover effects in SLX and SDEM models: while the first three specifications represent **global spillover effects**, the latter three represent **local spillover effects** <span class="co">[</span><span class="ot">@Anselin.2003; @LeSage.2009; @LeSage.2014</span><span class="co">]</span>. </span>
<span id="cb17-259"><a href="#cb17-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-260"><a href="#cb17-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### Local spillovers</span></span>
<span id="cb17-261"><a href="#cb17-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-262"><a href="#cb17-262" aria-hidden="true" tabindex="-1"></a>In case of SLX and SDEM the spatial spillover effects can be interpreted as the effect of a one unit change of ${\bm x}_k$ in the spatially weighted neighbouring observations on the dependent variable of the focal unit: the weighted average among neighbours; when using a row-normalised contiguity weights matrix, ${\bm W} {\bm x}_k$ is the mean value of ${\bm x}_k$ in the neighbouring units. </span>
<span id="cb17-263"><a href="#cb17-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-264"><a href="#cb17-264" aria-hidden="true" tabindex="-1"></a>Assume we have $k =2$ covariates, then</span>
<span id="cb17-265"><a href="#cb17-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-266"><a href="#cb17-266" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-267"><a href="#cb17-267" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-268"><a href="#cb17-268" aria-hidden="true" tabindex="-1"></a>\underbrace{\bm W}_{N \times N}  \underbrace{\bm X}_{N \times 2} \underbrace{\bm \theta}_{2 \times 1} &amp; = </span>
<span id="cb17-269"><a href="#cb17-269" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-270"><a href="#cb17-270" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-271"><a href="#cb17-271" aria-hidden="true" tabindex="-1"></a>      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 <span class="sc">\\</span></span>
<span id="cb17-272"><a href="#cb17-272" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0 <span class="sc">\\</span></span>
<span id="cb17-273"><a href="#cb17-273" aria-hidden="true" tabindex="-1"></a>      0.33 &amp; 0 &amp; 0.33 &amp; 0 &amp; 0.33 <span class="sc">\\</span></span>
<span id="cb17-274"><a href="#cb17-274" aria-hidden="true" tabindex="-1"></a>      0 &amp; 0.5 &amp; 0 &amp; 0.5 &amp; 0</span>
<span id="cb17-275"><a href="#cb17-275" aria-hidden="true" tabindex="-1"></a>  \end{pmatrix}</span>
<span id="cb17-276"><a href="#cb17-276" aria-hidden="true" tabindex="-1"></a>  \begin{pmatrix}</span>
<span id="cb17-277"><a href="#cb17-277" aria-hidden="true" tabindex="-1"></a>      3 &amp; 100 <span class="sc">\\</span></span>
<span id="cb17-278"><a href="#cb17-278" aria-hidden="true" tabindex="-1"></a>      4 &amp; 140 <span class="sc">\\</span></span>
<span id="cb17-279"><a href="#cb17-279" aria-hidden="true" tabindex="-1"></a>      1 &amp; 200 <span class="sc">\\</span></span>
<span id="cb17-280"><a href="#cb17-280" aria-hidden="true" tabindex="-1"></a>      7 &amp; 70  <span class="sc">\\</span></span>
<span id="cb17-281"><a href="#cb17-281" aria-hidden="true" tabindex="-1"></a>      5 &amp; 250 </span>
<span id="cb17-282"><a href="#cb17-282" aria-hidden="true" tabindex="-1"></a>  \end{pmatrix}</span>
<span id="cb17-283"><a href="#cb17-283" aria-hidden="true" tabindex="-1"></a>    \begin{pmatrix}</span>
<span id="cb17-284"><a href="#cb17-284" aria-hidden="true" tabindex="-1"></a>      \theta_1 <span class="sc">\\</span></span>
<span id="cb17-285"><a href="#cb17-285" aria-hidden="true" tabindex="-1"></a>      \theta_2 </span>
<span id="cb17-286"><a href="#cb17-286" aria-hidden="true" tabindex="-1"></a>  \end{pmatrix}<span class="sc">\\</span></span>
<span id="cb17-287"><a href="#cb17-287" aria-hidden="true" tabindex="-1"></a> &amp; =   </span>
<span id="cb17-288"><a href="#cb17-288" aria-hidden="true" tabindex="-1"></a> \begin{pmatrix}</span>
<span id="cb17-289"><a href="#cb17-289" aria-hidden="true" tabindex="-1"></a>      6 &amp; 105 <span class="sc">\\</span></span>
<span id="cb17-290"><a href="#cb17-290" aria-hidden="true" tabindex="-1"></a>      3 &amp; 190 <span class="sc">\\</span></span>
<span id="cb17-291"><a href="#cb17-291" aria-hidden="true" tabindex="-1"></a>      6 &amp; 105 <span class="sc">\\</span></span>
<span id="cb17-292"><a href="#cb17-292" aria-hidden="true" tabindex="-1"></a>      3 &amp; 190  <span class="sc">\\</span></span>
<span id="cb17-293"><a href="#cb17-293" aria-hidden="true" tabindex="-1"></a>      6 &amp; 105 </span>
<span id="cb17-294"><a href="#cb17-294" aria-hidden="true" tabindex="-1"></a>  \end{pmatrix}</span>
<span id="cb17-295"><a href="#cb17-295" aria-hidden="true" tabindex="-1"></a> \begin{pmatrix}</span>
<span id="cb17-296"><a href="#cb17-296" aria-hidden="true" tabindex="-1"></a>      \theta_1 <span class="sc">\\</span></span>
<span id="cb17-297"><a href="#cb17-297" aria-hidden="true" tabindex="-1"></a>      \theta_2</span>
<span id="cb17-298"><a href="#cb17-298" aria-hidden="true" tabindex="-1"></a>  \end{pmatrix}<span class="sc">\\</span></span>
<span id="cb17-299"><a href="#cb17-299" aria-hidden="true" tabindex="-1"></a>\end{split} </span>
<span id="cb17-300"><a href="#cb17-300" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-301"><a href="#cb17-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-304"><a href="#cb17-304" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-305"><a href="#cb17-305" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">x1 =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">8</span>,<span class="dv">5</span>),</span>
<span id="cb17-306"><a href="#cb17-306" aria-hidden="true" tabindex="-1"></a>           <span class="at">x2 =</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">140</span>,<span class="dv">200</span>,<span class="dv">70</span>,<span class="dv">270</span>))</span>
<span id="cb17-307"><a href="#cb17-307" aria-hidden="true" tabindex="-1"></a>(WX <span class="ot">&lt;-</span>  W <span class="sc">%*%</span> X)</span>
<span id="cb17-308"><a href="#cb17-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-309"><a href="#cb17-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-310"><a href="#cb17-310" aria-hidden="true" tabindex="-1"></a>Thus, only direct neighbours -- as defined in ${\bm W}$ -- contribute to those local spillover effects. The $\hat{\bm\theta}$ coefficients only estimate how my direct neighbour's $\bm X$ values influence my own outcome $\bm y$.</span>
<span id="cb17-311"><a href="#cb17-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-312"><a href="#cb17-312" aria-hidden="true" tabindex="-1"></a>There are no higher order neighbours involved (as long as we do not model them), nor are there any feedback loops due to interdependence.</span>
<span id="cb17-313"><a href="#cb17-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-314"><a href="#cb17-314" aria-hidden="true" tabindex="-1"></a><span class="fu">### Global spillovers</span></span>
<span id="cb17-315"><a href="#cb17-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-316"><a href="#cb17-316" aria-hidden="true" tabindex="-1"></a>In contrast, spillover effects in SAR, SAC, and SDM models do not only include direct neighbours but also neighbours of neighbours (second order neighbours) and further higher-order neighbours. This can be seen by rewriting the inverse $({\bm I_N}-\rho {\bm W})^{-1}$ as power series:A power series of $\sum\nolimits_{k=0}^\infty {\bm W}^k$ converges to $({\bm I}-{\bm W})^{-1}$ if the maximum absolute eigenvalue of ${\bm W} &lt; 1$, which is ensured by standardizing ${\bm W}$.}</span>
<span id="cb17-317"><a href="#cb17-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-318"><a href="#cb17-318" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-319"><a href="#cb17-319" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-320"><a href="#cb17-320" aria-hidden="true" tabindex="-1"></a>({\bm I_N}-\rho {\bm W})^{-1}\beta_k </span>
<span id="cb17-321"><a href="#cb17-321" aria-hidden="true" tabindex="-1"></a>=({\bm I_N} + \rho{\bm W} + \rho^2{\bm W}^2 + \rho^3{\bm W}^3 + ...)\beta_k </span>
<span id="cb17-322"><a href="#cb17-322" aria-hidden="true" tabindex="-1"></a>= ({\bm I_N} + \sum_{h=1}^\infty \rho^h{\bm W}^h)\beta_k ,</span>
<span id="cb17-323"><a href="#cb17-323" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-324"><a href="#cb17-324" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-325"><a href="#cb17-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-326"><a href="#cb17-326" aria-hidden="true" tabindex="-1"></a>where the identity matrix represents the direct effects and the sum represents the first and higher order indirect effects and the above mentioned feedback loops. This implies that a change in one unit $i$ does not only affect the direct neighbours but passes through the whole system towards higher-order neighbours, where the impact declines with distance within the neighbouring system. Global indirect impacts thus are `multiplied' by influencing direct neighbours as specified in $\bm W$ and indirect neighbours not connected according to $\bm W$, with additional feedback loops between those neighbours.</span>
<span id="cb17-327"><a href="#cb17-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-328"><a href="#cb17-328" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-329"><a href="#cb17-329" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-330"><a href="#cb17-330" aria-hidden="true" tabindex="-1"></a>\underbrace{(\underbrace{\bm I_N}_{N \times N} - \underbrace{\rho}_{\hat{=} 0.6} \underbrace{\bm W}_{N \times N})^{-1}}_{N \times N} \beta_k</span>
<span id="cb17-331"><a href="#cb17-331" aria-hidden="true" tabindex="-1"></a>&amp;=</span>
<span id="cb17-332"><a href="#cb17-332" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-333"><a href="#cb17-333" aria-hidden="true" tabindex="-1"></a>      1.\color{red}{1875} &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-334"><a href="#cb17-334" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; 1.\color{red}{28125} &amp; 0.3125 &amp; 0.28125 &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-335"><a href="#cb17-335" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; 1.\color{red}{1875} &amp; 0.46875 &amp; 0.1875 <span class="sc">\\</span></span>
<span id="cb17-336"><a href="#cb17-336" aria-hidden="true" tabindex="-1"></a>      0.3125 &amp; 0.28125 &amp; 0.3125 &amp; 1.\color{red}{28125} &amp; 0.3125 <span class="sc">\\</span></span>
<span id="cb17-337"><a href="#cb17-337" aria-hidden="true" tabindex="-1"></a>      0.1875 &amp; 0.46875 &amp; 0.1875 &amp; 0.46875 &amp; 1.\color{red}{1875}</span>
<span id="cb17-338"><a href="#cb17-338" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix}</span>
<span id="cb17-339"><a href="#cb17-339" aria-hidden="true" tabindex="-1"></a>  \begin{matrix}</span>
<span id="cb17-340"><a href="#cb17-340" aria-hidden="true" tabindex="-1"></a>      (\beta_1 + \beta_2)<span class="sc">\\</span></span>
<span id="cb17-341"><a href="#cb17-341" aria-hidden="true" tabindex="-1"></a>  \end{matrix}<span class="sc">\\</span>.</span>
<span id="cb17-342"><a href="#cb17-342" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-343"><a href="#cb17-343" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-344"><a href="#cb17-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-345"><a href="#cb17-345" aria-hidden="true" tabindex="-1"></a>All diagonal elements of $\mathrm{diag}({\bm W})=w_{ii}=0$. However, diagonal elements of higher order neighbours are not zero $\mathrm{diag}({\bm W}^2)=\mathrm{diag}({\bm W}{\bm W})\neq0$. </span>
<span id="cb17-346"><a href="#cb17-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-347"><a href="#cb17-347" aria-hidden="true" tabindex="-1"></a>Intuitively, $\rho{\bm W}$ only represents the effects between direct neighbours (and the focal unit is not a neighbour of the focal unit itself), whereas $\rho^2{\bm W}^2$ contains the effects of second order neighbours, where the focal unit is a second order neighbour of the focal unit itself. Thus, $({\bm I_N}-\rho {\bm W})^{-1}\beta_k$ includes <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:red"</span><span class="kw">&gt;</span>feedback effects<span class="kw">&lt;/span&gt;</span> from $\rho^2{\bm W}^2$ on (they are part of the direct impacts according to the summary measures below). This is way the <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:red"</span><span class="kw">&gt;</span>diagonal above<span class="kw">&lt;/span&gt;</span> $\geq 1$.</span>
<span id="cb17-348"><a href="#cb17-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-349"><a href="#cb17-349" aria-hidden="true" tabindex="-1"></a>In consequence, local and global spillover effects represent two distinct kinds of spatial spillover effects <span class="co">[</span><span class="ot">@LeSage.2014</span><span class="co">]</span>. The interpretation of local spillover effects is straightforward: it represents the effect of all neighbours as defined by ${\bm W}$ (the average over all neighbours in case of a row-normalised weights matrix). </span>
<span id="cb17-350"><a href="#cb17-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-351"><a href="#cb17-351" aria-hidden="true" tabindex="-1"></a>For instance, the environmental quality in the focal unit itself but also in neighbouring units could influence the attractiveness of a district and its house prices. In this example it seems reasonable to assume that we have local spillover effects: only the environmental quality in directly contiguous units (e.g. in walking distance) is relevant for estimating the house prices. </span>
<span id="cb17-352"><a href="#cb17-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-353"><a href="#cb17-353" aria-hidden="true" tabindex="-1"></a>In contrast, interpreting global spillover effects can be a bit more difficult. Intuitively, the global spillover effects can be seen as a kind of diffusion process. For example, an exogenous event might increase the house prices in one district of a city, thus leading to an adaptation of house prices in neighbouring districts, which then leads to further adaptations in other units (the neighbours of the neighbours), thereby globally diffusing the effect of the exogenous event due to the endogenous term. </span>
<span id="cb17-354"><a href="#cb17-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-355"><a href="#cb17-355" aria-hidden="true" tabindex="-1"></a>Yet, those processes happen over time. In a cross-sectional framework, the global spillover effects are hard to interpret. @Anselin.2003 proposes an interpretation as an equilibrium outcome, where the partial impact represents an estimate of how this long-run equilibrium would change due to a change in ${\bm x}_k$ <span class="co">[</span><span class="ot">@LeSage.2014</span><span class="co">]</span>.</span>
<span id="cb17-356"><a href="#cb17-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-357"><a href="#cb17-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-358"><a href="#cb17-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-359"><a href="#cb17-359" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary impact measures</span></span>
<span id="cb17-360"><a href="#cb17-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-361"><a href="#cb17-361" aria-hidden="true" tabindex="-1"></a>Note that the derivative in SAR, SAC, and SDM is a $N \times N$ matrix, returning individual effects of each unit on each other unit, differentiated in _direct, indirect, and total impacts_. </span>
<span id="cb17-362"><a href="#cb17-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-363"><a href="#cb17-363" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-364"><a href="#cb17-364" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-365"><a href="#cb17-365" aria-hidden="true" tabindex="-1"></a>(\bm I_N - \rho \bm W)^{-1} \beta &amp;=</span>
<span id="cb17-366"><a href="#cb17-366" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-367"><a href="#cb17-367" aria-hidden="true" tabindex="-1"></a>      \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} <span class="sc">\\</span></span>
<span id="cb17-368"><a href="#cb17-368" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} <span class="sc">\\</span></span>
<span id="cb17-369"><a href="#cb17-369" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} <span class="sc">\\</span></span>
<span id="cb17-370"><a href="#cb17-370" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} <span class="sc">\\</span></span>
<span id="cb17-371"><a href="#cb17-371" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875}</span>
<span id="cb17-372"><a href="#cb17-372" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix} \beta</span>
<span id="cb17-373"><a href="#cb17-373" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-374"><a href="#cb17-374" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-375"><a href="#cb17-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-376"><a href="#cb17-376" aria-hidden="true" tabindex="-1"></a>**However, the individual effects (how $i$ influences $j$) mainly vary because of variation in ${\bm W}$. **</span>
<span id="cb17-377"><a href="#cb17-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-378"><a href="#cb17-378" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb17-379"><a href="#cb17-379" aria-hidden="true" tabindex="-1"></a><span class="fu">### Do not interpret these as "estimated" individual impacts</span></span>
<span id="cb17-380"><a href="#cb17-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-381"><a href="#cb17-381" aria-hidden="true" tabindex="-1"></a>We estimate two scalar parameters in a SAR model: $\beta$ for the direct coefficient and $rho$ for the auto-regressive parameter.</span>
<span id="cb17-382"><a href="#cb17-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-383"><a href="#cb17-383" aria-hidden="true" tabindex="-1"></a>All variation in the effects matrix $(\bm I_N - \rho \bm W)^{-1}$ \beta comes from the relationship in $\bm W$ which we have given a-priori!</span>
<span id="cb17-384"><a href="#cb17-384" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-385"><a href="#cb17-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-386"><a href="#cb17-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-387"><a href="#cb17-387" aria-hidden="true" tabindex="-1"></a>Since reporting the individual partial effects is usually not of interest, @LeSage.2009 proposed to average over these effect matrices. While the average diagonal elements of the effects matrix $(\bm I_N - \rho \bm W)^{-1}$ represent the so called direct impacts of variable ${\bm x}_k$, the average column-sums of the off-diagonal elements represent the so called indirect impacts (or spatial spillover effects). </span>
<span id="cb17-388"><a href="#cb17-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-389"><a href="#cb17-389" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:red"</span><span class="kw">&gt;</span>direct impacts<span class="kw">&lt;/span&gt;</span> refer to an average effect of a unit change in $x_i$ on $y_i$, and <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:blue"</span><span class="kw">&gt;</span>the indirect (spillover) impacts<span class="kw">&lt;/span&gt;</span>  indicate how a change in $x_i$, on average, influences all neighbouring units $y_j$.</span>
<span id="cb17-390"><a href="#cb17-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-391"><a href="#cb17-391" aria-hidden="true" tabindex="-1"></a>Though previous literature <span class="co">[</span><span class="ot">@HalleckVega.2015; @LeSage.2009</span><span class="co">]</span> has established the notation of direct and indirect impacts, it is important to note that also the direct impacts comprise a spatial `multiplier' component if we specify an endogenous lagged depended variable, as a change in $\bm x_i$ influences $\bm y_i$, which influences $\bm y_j$, which in turn influences $\bm y_i$.</span>
<span id="cb17-392"><a href="#cb17-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-393"><a href="#cb17-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-394"><a href="#cb17-394" aria-hidden="true" tabindex="-1"></a>Usually, one should use summary measures to report effects in spatial models <span class="co">[</span><span class="ot">@LeSage.2009</span><span class="co">]</span>. @HalleckVega.2015 provide a nice summary of the impacts for each model:</span>
<span id="cb17-395"><a href="#cb17-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-396"><a href="#cb17-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-397"><a href="#cb17-397" aria-hidden="true" tabindex="-1"></a>Model | Direct Impacts | Indirect Impacts | type</span>
<span id="cb17-398"><a href="#cb17-398" aria-hidden="true" tabindex="-1"></a>:-: | :-: | :-: | :-:</span>
<span id="cb17-399"><a href="#cb17-399" aria-hidden="true" tabindex="-1"></a>OLS/SEM | $\beta_k$ | -- | --</span>
<span id="cb17-400"><a href="#cb17-400" aria-hidden="true" tabindex="-1"></a>SAR/SAC | <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:red"</span><span class="kw">&gt;</span>Diagonal elements<span class="kw">&lt;/span&gt;</span> of $({\bm I}-\rho{\bm W})^{-1}\beta_k$ | <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:blue"</span><span class="kw">&gt;</span>Off-diagonal elements<span class="kw">&lt;/span&gt;</span>  of $({\bm I}-\rho{\bm W})^{-1}\beta_k$ | global</span>
<span id="cb17-401"><a href="#cb17-401" aria-hidden="true" tabindex="-1"></a>SLX/SDEM | $\beta_k$ | $\theta_k$ | local</span>
<span id="cb17-402"><a href="#cb17-402" aria-hidden="true" tabindex="-1"></a>SDM | <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:red"</span><span class="kw">&gt;</span>Diagonal elements<span class="kw">&lt;/span&gt;</span>  of $({\bm I}-\rho{\bm W})^{-1}\left<span class="co">[</span><span class="ot">\beta_k+{\bm W}\theta_k\right</span><span class="co">]</span>$ | <span class="kw">&lt;span</span> <span class="er">style</span><span class="ot">=</span><span class="st">"color:blue"</span><span class="kw">&gt;</span>Off-diagonal elements<span class="kw">&lt;/span&gt;</span> of $({\bm I}-\rho{\bm W})^{-1}$ |global</span>
<span id="cb17-403"><a href="#cb17-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-404"><a href="#cb17-404" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-405"><a href="#cb17-405" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb17-406"><a href="#cb17-406" aria-hidden="true" tabindex="-1"></a>(\bm I_N - \rho \bm W)^{-1} \beta &amp;=</span>
<span id="cb17-407"><a href="#cb17-407" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb17-408"><a href="#cb17-408" aria-hidden="true" tabindex="-1"></a>      \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} <span class="sc">\\</span></span>
<span id="cb17-409"><a href="#cb17-409" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} <span class="sc">\\</span></span>
<span id="cb17-410"><a href="#cb17-410" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} <span class="sc">\\</span></span>
<span id="cb17-411"><a href="#cb17-411" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.3125} &amp; \color{blue}{0.28125} &amp; \color{blue}{0.3125} &amp; \color{red}{1.28125} &amp; \color{blue}{0.3125} <span class="sc">\\</span></span>
<span id="cb17-412"><a href="#cb17-412" aria-hidden="true" tabindex="-1"></a>      \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{blue}{0.1875} &amp; \color{blue}{0.46875} &amp; \color{red}{1.1875}</span>
<span id="cb17-413"><a href="#cb17-413" aria-hidden="true" tabindex="-1"></a>      \end{pmatrix} \beta</span>
<span id="cb17-414"><a href="#cb17-414" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb17-415"><a href="#cb17-415" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb17-416"><a href="#cb17-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-417"><a href="#cb17-417" aria-hidden="true" tabindex="-1"></a>The different indirect effects / spatial effects mean conceptually different things:</span>
<span id="cb17-418"><a href="#cb17-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-419"><a href="#cb17-419" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Global spillover effects: SAR, SAC, SDM</span>
<span id="cb17-420"><a href="#cb17-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-421"><a href="#cb17-421" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Local spillover effects: SLX, SDEM</span>
<span id="cb17-422"><a href="#cb17-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-423"><a href="#cb17-423" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb17-424"><a href="#cb17-424" aria-hidden="true" tabindex="-1"></a><span class="fu">### Common ratio between direct and indirect impacts in SAR and SAC</span></span>
<span id="cb17-425"><a href="#cb17-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-426"><a href="#cb17-426" aria-hidden="true" tabindex="-1"></a>Note that impacts in SAR only estimate one single spatial multiplier coefficient. Thus direct and indirect impacts are bound to a common ratio, say $\phi$, across all covariates.</span>
<span id="cb17-427"><a href="#cb17-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-428"><a href="#cb17-428" aria-hidden="true" tabindex="-1"></a>if $\beta_1^{direct} = \phi\beta_1^{indirect}$, then $\beta_2^{direct} = \phi\beta_2^{indirect}$, $\beta_k^{direct} = \phi\beta_k^{indirect}$. </span>
<span id="cb17-429"><a href="#cb17-429" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-430"><a href="#cb17-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-431"><a href="#cb17-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-432"><a href="#cb17-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-433"><a href="#cb17-433" aria-hidden="true" tabindex="-1"></a>We can calculate these impacts using <span class="in">`impacts()`</span> with simulated distributions, e.g. for the SAR model:</span>
<span id="cb17-434"><a href="#cb17-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-437"><a href="#cb17-437" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-438"><a href="#cb17-438" aria-hidden="true" tabindex="-1"></a>mod_1.sar.imp <span class="ot">&lt;-</span> <span class="fu">impacts</span>(mod_1.sar, <span class="at">listw =</span> queens.lw, <span class="at">R =</span> <span class="dv">300</span>)</span>
<span id="cb17-439"><a href="#cb17-439" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_1.sar.imp, <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-440"><a href="#cb17-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-441"><a href="#cb17-441" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative with traces (better for large W)</span></span>
<span id="cb17-442"><a href="#cb17-442" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as</span>(queens.lw, <span class="st">"CsparseMatrix"</span>)</span>
<span id="cb17-443"><a href="#cb17-443" aria-hidden="true" tabindex="-1"></a>trMatc <span class="ot">&lt;-</span> <span class="fu">trW</span>(W, <span class="at">type =</span> <span class="st">"mult"</span>,</span>
<span id="cb17-444"><a href="#cb17-444" aria-hidden="true" tabindex="-1"></a>              <span class="at">m =</span> <span class="dv">30</span>) <span class="co"># number of powers</span></span>
<span id="cb17-445"><a href="#cb17-445" aria-hidden="true" tabindex="-1"></a>mod_1.sar.imp2 <span class="ot">&lt;-</span> <span class="fu">impacts</span>(mod_1.sar, </span>
<span id="cb17-446"><a href="#cb17-446" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tr =</span> trMatc, <span class="co"># trace instead of listw</span></span>
<span id="cb17-447"><a href="#cb17-447" aria-hidden="true" tabindex="-1"></a>                          <span class="at">R =</span> <span class="dv">300</span>, </span>
<span id="cb17-448"><a href="#cb17-448" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Q =</span> <span class="dv">30</span>) <span class="co"># number of power series used for approximation</span></span>
<span id="cb17-449"><a href="#cb17-449" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_1.sar.imp2, <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-450"><a href="#cb17-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-451"><a href="#cb17-451" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-452"><a href="#cb17-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-453"><a href="#cb17-453" aria-hidden="true" tabindex="-1"></a>The indirect effects in SAR, SAC, and SDM refer to global spillover effects. This means a change of $x$ in the focal units flows through the entire system of neighbours (direct nieightbours, neighbours of neighbours, ...) influencing 'their $y$'. One can think of this as diffusion or a change in a long-term equilibrium.</span>
<span id="cb17-454"><a href="#cb17-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-455"><a href="#cb17-455" aria-hidden="true" tabindex="-1"></a>_If population density increases by one unit, this increases the house price in the focal unit by `r round(mod_1.sar.imp$res$direct[1], 3)` units. Overall, a one unit change in population density increases the house prices in the entire neighbourhood system (direct and higher order neighbours) by  `r round(mod_1.sar.imp$res$indirect[1], 3)`._</span>
<span id="cb17-456"><a href="#cb17-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-457"><a href="#cb17-457" aria-hidden="true" tabindex="-1"></a>For SLX models, nothing is gained from computing the impacts, as they equal the coefficients. Again, it's the effects of direct neighbours only.</span>
<span id="cb17-458"><a href="#cb17-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-461"><a href="#cb17-461" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-462"><a href="#cb17-462" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">impacts</span>(mod_1.slx, <span class="at">listw =</span> queens.lw))</span>
<span id="cb17-463"><a href="#cb17-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-464"><a href="#cb17-464" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-465"><a href="#cb17-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-466"><a href="#cb17-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-467"><a href="#cb17-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-468"><a href="#cb17-468" aria-hidden="true" tabindex="-1"></a><span class="fu">## Examples</span></span>
<span id="cb17-469"><a href="#cb17-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-470"><a href="#cb17-470" aria-hidden="true" tabindex="-1"></a><span class="fu">### @Boillat.2022  {.unnumbered}</span></span>
<span id="cb17-471"><a href="#cb17-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-472"><a href="#cb17-472" aria-hidden="true" tabindex="-1"></a>_The paper investigates the effects of protected areas and various land tenure regimes on deforestation and possible spillover effects in Bolivia, a global tropical deforestation hotspot._</span>
<span id="cb17-473"><a href="#cb17-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-474"><a href="#cb17-474" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig/Boillat.png)</span></span>
<span id="cb17-475"><a href="#cb17-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-476"><a href="#cb17-476" aria-hidden="true" tabindex="-1"></a>_Protected areas – which in Bolivia are all based on co-management schemes - also protect forests in adjacent areas, showing an indirect protective spillover effect. Indigenous lands however only have direct forest protection effects._</span>
<span id="cb17-477"><a href="#cb17-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-478"><a href="#cb17-478" aria-hidden="true" tabindex="-1"></a><span class="fu">### @Fischer.2009  {.unnumbered}</span></span>
<span id="cb17-479"><a href="#cb17-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-480"><a href="#cb17-480" aria-hidden="true" tabindex="-1"></a>_The focus of this paper is on the role of human capital in explaining labor productivity variation among 198 European regions within a regression framework._</span>
<span id="cb17-481"><a href="#cb17-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-482"><a href="#cb17-482" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig/Fischer.png)</span></span>
<span id="cb17-483"><a href="#cb17-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-484"><a href="#cb17-484" aria-hidden="true" tabindex="-1"></a>_A ceteris paribus increase in the level of human capital is found to have a significant and positive direct impact. But this positive direct impact is offset by a significant and negative indirect (spillover) impact leading to a total impact that is not significantly different from zero._</span>
<span id="cb17-485"><a href="#cb17-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-486"><a href="#cb17-486" aria-hidden="true" tabindex="-1"></a>_The intuition here arises from the notion that it is relative regional advantages in human capital that matter most for labor productivity, so changing human capital across all regions should have little or no total impact on (average) labor productivity levels._</span>
<span id="cb17-487"><a href="#cb17-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-488"><a href="#cb17-488" aria-hidden="true" tabindex="-1"></a><span class="fu">### @Ruttenauer.2018a  {.unnumbered}</span></span>
<span id="cb17-489"><a href="#cb17-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-490"><a href="#cb17-490" aria-hidden="true" tabindex="-1"></a>_This study investigates the presence of environmental inequality in Germany - the connection between the presence of foreign-minority population and objectively measured industrial pollution._</span>
<span id="cb17-491"><a href="#cb17-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-492"><a href="#cb17-492" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig/census.png)</span></span>
<span id="cb17-493"><a href="#cb17-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-494"><a href="#cb17-494" aria-hidden="true" tabindex="-1"></a>_Results reveal that the share of minorities within a census cell indeed positively correlates with the exposure to industrial pollution. Furthermore, spatial spillover effects are highly relevant: the characteristics of the neighbouring spatial units matter in predicting the amount of pollution. Especially within urban areas, clusters of high minority neighbourhoods are affected by high levels of environmental pollution._</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>